// English is the primary content reference. Business amounts, counts and timing
// are intentionally absent here; those come from shared/service-facts.mjs.
export const approvedCopy = {
  en: {
    hero: ['Know your supplier.', 'Before you pay.'],
    context: 'Independent supplier verification in China',
    heroLead: 'We check the company behind the quote, the documents behind the claims, and what still needs an answer.',
    discuss: 'Discuss a supplier', compare: 'Compare services',
    principle: ['Working for the buyer.', 'No supplier commissions.'],
    focus: 'Specialist focus', products: 'Chargers, power adapters & power banks', base: 'Coordinated from', bases: 'Taiwan & Shenzhen',
    photoAlt: 'A component-placement machine working over an electronic circuit board.',
    photoCaption: 'Electronics manufacturing. Context photography, not a ZimonAI assignment.',
    photoCredit: 'Photo source', photoChanges: 'Resized and cropped for layout. The location and any relationship with ZimonAI are not asserted.',
    evidenceTitle: ['A genuine certificate.', 'But is it the right one?'],
    evidenceLead: 'A document can be authentic and still belong to a different company or exclude the model you plan to buy.',
    checks: [
      ['The company', 'Match the Chinese legal name behind the quotation to the business-registration record.'],
      ['The certificate', 'Check the issuer’s record, the certificate holder, its status and the models it covers.'],
      ['The remaining questions', 'Keep confirmed facts, discrepancies and unavailable evidence separate. A missing record is not proof of fraud.']
    ],
    how: 'How we verify supplier claims', reportTitle: 'An actual report artifact',
    reportLead: 'The cover of our existing English sample, shown unchanged. It is not a new supplier finding.',
    reportAlt: 'Unaltered cover of ZimonAI’s existing Supplier Verification Report sample.',
    reportOpen: 'Inspect the original cover', reportGapTitle: 'Report-preview limitation',
    reportGap: 'A publication-cleared, anonymized report interior is not available here. No case data has been invented to replace it.',
    servicesTitle: ['Start with the question.', 'Choose the depth.'],
    servicesLead: 'Two defined remote services. Fieldwork and ongoing support are scoped separately.',
    t1Fit: 'For a first supplier check', t2Fit: 'When the company needs a closer look',
    t1Action: 'Review T1 scope', t2Action: 'Review T2 scope', checkLabel: 'What we check', deliveryLabel: 'Delivery',
    advanced: 'Advanced', advancedLead: 'For assignments that need supplier interviews, site visits or continuing verification support.',
    scopeFirst: 'Scoped before work begins.', consentNote: 'Supplier cooperation and written consent may be required.',
    advancedAction: 'Discuss an advanced requirement', timingNote: 'Delivery timing starts after payment is confirmed and all required information is complete.',
    disclaimer: 'Verification supports a purchasing decision. It is not certification, a product-quality guarantee or a guarantee of future supplier performance.',
    servicePageTitle: 'The right scope for the decision in front of you.',
    servicePageLead: 'Start with identity and certificate checks, add deeper company research, or discuss an assignment that needs direct access.',
    serviceIndex: 'Choose your scope', researchDetail: 'See the checks and source limitations', suitable: 'When this fits',
    methodTitle: 'How we verify supplier claims',
    methodLead: 'A verification report should show how each conclusion was reached—and where the evidence runs out.',
    methodPath: 'What we examine', methodPathLead: 'Different questions require different records. Read the checks below; these describe the method, not a completed supplier case.',
    methodReport: 'A conclusion you can question',
    aboutTitle: 'A research and verification desk on the buyer’s side.',
    aboutLead: 'Charger and power-electronics sourcing, coordinated between Taiwan and Shenzhen. Paid by the client, not the supplier under review.',
    requestTitle: 'Which supplier decision do you need to make?',
    requestLead: 'Tell us about the supplier, product and claim you want checked. We will confirm the appropriate scope before work begins.',
    formTitle: 'Your requirement', privacyLink: 'How we handle your information',
    footerServices: 'Verification services', footerResources: 'Before you decide',
    menuMain: 'Start with the scope you need', menuAdvanced: 'Advanced engagements', menuNote: 'T1 and T2 are remote reviews. Supplier contact and fieldwork require a separate agreed scope.',
    knowledgeLead: 'Industry knowledge and current developments', closeMenu: 'Close menu', language: 'Language',
    brandDescriptor: 'Supplier verification in China',
    menuT1: 'Company identity and certificate checks', menuT2: 'Deeper company and relationship research',
    menuCustomTitle: 'Advanced & custom services',
    menuCustomDescription: 'Supplier interviews, site visits and ongoing support',
    photoContext: 'Context photography—not a client product, inspection or compliance finding.',
    boardAlt: 'An electronic power-supply board with capacitors, transformers and heat sinks.',
    boardCaption: 'Start with the actual product, then identify the records that apply.',
    chargersAlt: 'Two multiport chargers photographed on a table.',
    chargersCaption: 'The company, product model and supporting documents need to match.',
    manufacturingCaption: 'Supplier contact and site work are separately scoped—not included in T1 or T2.',
    methodPhotoLink: 'Explore the checks below'
  },
  'zh-tw': {
    hero: ['付款之前，', '先查清楚供應商。'],
    context: '中國供應商獨立查核',
    heroLead: '核對報價背後的公司、文件能支持的說法，以及哪些關鍵問題仍然沒有答案。',
    discuss: '討論供應商需求', compare: '比較服務範圍',
    principle: ['站在買家這一邊。', '不收供應商回扣。'],
    focus: '專注領域', products: '充電器、電源供應器與行動電源', base: '協作據點', bases: '台灣與深圳',
    photoAlt: '電子元件貼裝設備正在電路板上作業。',
    photoCaption: '電子製造情境實拍，非 ZimonAI 委託案件或查核現場。',
    photoCredit: '照片來源', photoChanges: '照片經縮放與版面裁切；不據此宣稱拍攝地點或與 ZimonAI 有合作關係。',
    evidenceTitle: ['證書是真的，', '就代表適用嗎？'],
    evidenceLead: '文件本身可能是真實的，卻屬於另一家公司，或根本沒有涵蓋你打算採購的型號。',
    checks: [
      ['公司主體', '將報價背後的中文法律名稱，與企業登記紀錄核對。'],
      ['證書範圍', '查閱發證機構的紀錄，核對持有人、狀態與涵蓋型號。'],
      ['尚待確認的事', '分清楚已確認事實、資料矛盾與無法取得的證據。查不到，不等於已證明詐欺。']
    ],
    how: '了解我們如何核對供應商說法', reportTitle: '既有報告的真實封面',
    reportLead: '直接展示現有英文範例的原始封面，不代表新的供應商查核結果。',
    reportAlt: 'ZimonAI 既有 Supplier Verification Report 英文範例原始封面。',
    reportOpen: '查看原始封面', reportGapTitle: '報告預覽限制',
    reportGap: '目前不展示尚未完成公開審核的匿名化內頁，也不以虛構案件資料補位。',
    servicesTitle: ['從問題出發，', '選擇需要的查核深度。'],
    servicesLead: '兩項固定範圍的遠端服務；實地工作與持續協助則另行確認範圍。',
    t1Fit: '第一次查核供應商', t2Fit: '需要深入了解公司背景時',
    t1Action: '查看 T1 範圍', t2Action: '查看 T2 範圍', checkLabel: '查核內容', deliveryLabel: '交付內容',
    advanced: '進階服務', advancedLead: '需要供應商訪談、實地查核，或持續性查核協助的案件。',
    scopeFirst: '先確認範圍，再開始工作。', consentNote: '依案件需求，可能須取得供應商配合與書面同意。',
    advancedAction: '討論進階查核需求', timingNote: '付款確認且必要資料完整後，才開始計算交付時間。',
    disclaimer: '查核提供採購判斷所需的資訊，不是認證、產品品質保證，也不保證供應商未來履約。',
    servicePageTitle: '依你要做的決定，選擇合適的查核範圍。',
    servicePageLead: '從公司身分與證書核對開始，加深企業背景研究，或討論需要直接接觸供應商的案件。',
    serviceIndex: '選擇查核範圍', researchDetail: '查看查核項目與資料限制', suitable: '適合什麼情況',
    methodTitle: '我們如何查核供應商的說法',
    methodLead: '一份查核報告應讓你看得懂結論如何形成，也知道證據到哪裡為止。',
    methodPath: '我們會查什麼', methodPathLead: '不同問題需要不同紀錄。以下說明查核方法，不是已完成的供應商個案。',
    methodReport: '讓結論經得起提問',
    aboutTitle: '站在買家這邊的供應商研究與查核。',
    aboutLead: '專注充電器與電源電子供應鏈，由台灣與深圳協作。付費客戶是買家，不是受查核的供應商。',
    requestTitle: '你正面臨哪一個供應商決定？',
    requestLead: '告訴我們供應商、產品，以及需要核對的說法。開始工作前，我們會先確認適合的查核範圍。',
    formTitle: '你的需求', privacyLink: '我們如何處理你的資料',
    footerServices: '供應商查核服務', footerResources: '決定前先了解',
    menuMain: '從需要的查核範圍開始', menuAdvanced: '進階委託項目', menuNote: 'T1、T2 為遠端研究；供應商聯絡與實地工作須另行確認範圍。',
    knowledgeLead: '產業知識與重要時事', closeMenu: '關閉選單', language: '語言',
    brandDescriptor: '中國供應商查核',
    menuT1: '公司身分與證書核對', menuT2: '深入企業背景與關聯研究',
    menuCustomTitle: '進階與客製化服務',
    menuCustomDescription: '供應商訪談、實地查核與持續性協助',
    photoContext: '情境實拍，非客戶產品、查核現場或合規查核結果。',
    boardAlt: '裝有電容、變壓器與散熱片的電源電路板。',
    boardCaption: '先釐清實際產品，再確認適用的查核紀錄。',
    chargersAlt: '桌上兩個多孔充電器的實拍照片。',
    chargersCaption: '公司、產品型號與佐證文件，需要彼此對得上。',
    manufacturingCaption: '供應商聯絡與實地工作另行確認範圍，不包含在 T1 或 T2。',
    methodPhotoLink: '查看下方查核項目'
  },
  'zh-cn': {
    hero: ['付款之前，', '先查清供应商。'],
    context: '中国供应商独立核查',
    heroLead: '核对报价背后的公司、文件能够支持的说法，以及哪些关键问题仍然没有答案。',
    discuss: '讨论供应商需求', compare: '比较服务范围',
    principle: ['站在买家这一边。', '不收供应商回扣。'],
    focus: '专注领域', products: '充电器、电源适配器与移动电源', base: '协作地点', bases: '台湾与深圳',
    photoAlt: '电子元件贴装设备正在电路板上作业。',
    photoCaption: '电子制造实拍，用于说明行业场景，并非 ZimonAI 委托项目或核查现场。',
    photoCredit: '照片来源', photoChanges: '照片经过缩放与版面裁切；不据此声明拍摄地点或与 ZimonAI 存在合作关系。',
    evidenceTitle: ['证书是真的，', '就代表适用吗？'],
    evidenceLead: '文件本身可能是真实的，却属于另一家公司，或者没有覆盖你计划采购的型号。',
    checks: [
      ['公司主体', '将报价背后的中文法定名称，与企业登记记录核对。'],
      ['证书范围', '查询发证机构的记录，核对持有人、状态与覆盖型号。'],
      ['仍待确认的问题', '区分已核实事实、资料矛盾和无法获取的证据。查不到，不等于已经证实欺诈。']
    ],
    how: '了解我们如何核对供应商说法', reportTitle: '现有报告的真实封面',
    reportLead: '直接展示现有英文示例的原始封面，不代表新的供应商核查结果。',
    reportAlt: 'ZimonAI 现有 Supplier Verification Report 英文示例的原始封面。',
    reportOpen: '查看原始封面', reportGapTitle: '报告预览限制',
    reportGap: '目前不展示尚未完成公开审核的匿名化内页，也不使用虚构项目数据填补。',
    servicesTitle: ['从问题出发，', '选择需要的核查深度。'],
    servicesLead: '两项固定范围的远程服务；现场工作和持续支持则另行确认范围。',
    t1Fit: '首次核查供应商', t2Fit: '需要深入了解公司背景时',
    t1Action: '查看 T1 范围', t2Action: '查看 T2 范围', checkLabel: '核查内容', deliveryLabel: '交付内容',
    advanced: '进阶服务', advancedLead: '适用于需要供应商访谈、现场核查或持续核查支持的项目。',
    scopeFirst: '先确认范围，再开始工作。', consentNote: '根据项目要求，可能需要供应商配合及书面同意。',
    advancedAction: '讨论进阶核查需求', timingNote: '付款确认且必要资料齐全后，才开始计算交付时间。',
    disclaimer: '核查提供采购判断所需的信息，不是认证或产品质量保证，也不保证供应商未来履约。',
    servicePageTitle: '根据你要做的决定，选择合适的核查范围。',
    servicePageLead: '从公司身份和证书核对开始，深化企业背景研究，或讨论需要直接接触供应商的项目。',
    serviceIndex: '选择核查范围', researchDetail: '查看核查项目与资料限制', suitable: '适合什么情况',
    methodTitle: '我们如何核查供应商的说法',
    methodLead: '一份核查报告应当让你理解结论如何形成，也知道证据到哪里为止。',
    methodPath: '我们会核查什么', methodPathLead: '不同问题需要不同记录。以下说明核查方法，并非已经完成的供应商案例。',
    methodReport: '让结论经得起追问',
    aboutTitle: '站在买家一方的供应商研究与核查。',
    aboutLead: '专注充电器与电源电子供应链，由台湾和深圳协作。付费客户是买家，而不是被核查的供应商。',
    requestTitle: '你正面临哪一个供应商决定？',
    requestLead: '告诉我们供应商、产品，以及需要核对的说法。开始工作前，我们会先确认适合的核查范围。',
    formTitle: '你的需求', privacyLink: '我们如何处理你的信息',
    footerServices: '供应商核查服务', footerResources: '决定前先了解',
    menuMain: '从需要的核查范围开始', menuAdvanced: '进阶委托项目', menuNote: 'T1、T2 为远程研究；供应商联系与现场工作须另行确认范围。',
    knowledgeLead: '行业知识与重要时事', closeMenu: '关闭菜单', language: '语言',
    brandDescriptor: '中国供应商核查',
    menuT1: '公司身份与证书核对', menuT2: '深入企业背景与关联研究',
    menuCustomTitle: '进阶与定制服务',
    menuCustomDescription: '供应商访谈、现场核查与持续支持',
    photoContext: '真实情境照片，非客户产品、核查现场或合规核查结果。',
    boardAlt: '装有电容、变压器和散热片的电源电路板。',
    boardCaption: '先明确实际产品，再确认适用的核查记录。',
    chargersAlt: '桌上两个多口充电器的实拍照片。',
    chargersCaption: '公司、产品型号与佐证文件，需要相互对应。',
    manufacturingCaption: '供应商联系与现场工作另行确认范围，不包含在 T1 或 T2。',
    methodPhotoLink: '查看下方核查项目'
  }
};
