import { knowledgePageDefinitions } from './knowledge-content.mjs';

export const pages = [
  { id: 'home', slug: '' },
  { id: 'services', slug: 'services' },
  { id: 'methodology', slug: 'methodology' },
  { id: 'scope', slug: 'scope-limitations' },
  { id: 'about', slug: 'about' },
  { id: 'portal', slug: 'portal', sitemap: false, noindex: true },
  { id: 'admin', slug: 'admin', sitemap: false, noindex: true },
  { id: 'request', slug: 'request-verification' },
  { id: 'payments', slug: 'payments' },
  { id: 'paymentTerms', slug: 'payment-terms' },
  { id: 'paymentSuccess', slug: 'payment-success', sitemap: false, noindex: true },
  { id: 'privacy', slug: 'privacy' },
  ...knowledgePageDefinitions
];

export const languages = {
  en: {
    prefix: '', htmlLang: 'en', locale: 'en_US', short: 'EN', name: 'English',
    meta: {
      titles: { home: 'Charger Supplier Verification in China | ZimonAI', services: 'T1–T6 Charger Supplier Verification Services | ZimonAI', methodology: 'Charger Supplier Verification Methodology | ZimonAI', scope: 'Supplier Verification Scope & Limits | ZimonAI', about: 'About ZimonAI | Taiwan × Shenzhen', request: 'Discuss a Charger Supplier Requirement | ZimonAI', privacy: 'Privacy Notice | ZimonAI' },
      descriptions: { home: 'Verify charger, power adapter and power bank suppliers in China before payment. Company records, FCC and UL claims, remote due diligence and agreed on-site checks.', services: 'Compare ZimonAI T1–T6 charger and power electronics supplier services, from remote certificate checks to managed sourcing verification.', methodology: 'See how ZimonAI checks Chinese company records, FCC IDs, UL files, model scope and supplier claims using a traceable evidence method.', scope: 'Understand the agreed scope, supplier consent and limitations of charger supplier verification and quality work.', about: 'ZimonAI is a client-paid charger and power electronics specialist coordinated between Taiwan and Shenzhen.', request: 'Tell ZimonAI which charger, power adapter, power bank supplier or certification claim you need checked.', privacy: 'How ZimonAI handles information you choose to send when discussing supplier services.' }
    },
    nav: { services: 'Services', servicesBooking: 'Services & booking', methodology: 'Methodology', scope: 'Scope & limits', about: 'About', knowledge: 'Knowledge', request: 'Discuss a requirement', menu: 'Menu', close: 'Close' },
    ui: { supplierProfile: 'Supplier profile', claimedSince: 'Claimed since', certification: 'Certification', factory: 'Factory', evidencePath: 'ZM / Evidence path', compare: 'Compare', registryRecord: 'Registry / certificate record', inScope: 'In scope', deliverable: 'What you receive', whatWeCheck: 'What we check', whyItMatters: 'Why it matters', sourceType: 'Source type', possibleResult: 'Possible result', origin: 'Origin', model: 'Business model', footprint: 'Operating footprint', scale: 'Engagement principle', operatingRecord: 'Operating record', suppliedMaterial: 'What you send', reviewWork: 'What we review', reportField: 'Report field', openEvidence: 'Open evidence' },
    common: { skip: 'Skip to content', eyebrow: 'Charger & power electronics', brandDescriptor: 'Charger & Power Electronics Verification', demo: 'Demonstration · Fictional supplier', verified: 'Verified', unresolved: 'Unable to verify', discrepancy: 'Discrepancy found', pending: 'Pending', source: 'Source', claim: 'Supplier claim', record: 'Official record', result: 'Result', queryDate: 'Query date', reference: 'Reference', email: 'Email', chinaPhone: 'China phone', taiwanPhone: 'Taiwan phone', whatsapp: 'WhatsApp', wechat: 'WeChat', line: 'LINE ID', linkedin: 'LinkedIn', contact: 'Discuss your requirement', methodology: 'See how we verify', independent: 'Client-paid; no supplier kickbacks', footerLine: 'Find the right supplier. Verify the facts. Check the product.', footerCategory: 'Charger & power electronics supplier verification', creditCodeLabel: 'Unified Social Credit Code', chineseAddressLabel: 'Chinese address', englishAddressLabel: 'English address', officesLabel: 'Office locations', shenzhenOffice: 'Shenzhen Office', shenzhenOfficeRole: 'Company registration and China-side execution', taiwanOffice: 'Taiwan Office · New Taipei', taiwanOfficeRole: 'Client communication and project coordination', appointmentOnly: 'Meetings by appointment', footerScope: 'Supplier recommendations, verification and quality work are scoped and priced before each assignment begins.', privacy: 'Privacy', language: 'Language', top: 'Back to top', current: 'Current page' },
    home: {
      kicker: 'Before a commercial commitment', title: 'Know who you are buying from—and what you are receiving.', categoryLine: 'Charger, power adapter and power bank suppliers in Shenzhen—verified before you pay.', lead: 'ZimonAI helps overseas buyers screen suppliers, verify company and certification records, and carry out agreed product and on-site checks for charger and power electronics assignments.', primary: 'Discuss your requirement', secondary: 'See how we verify', distinction: 'One product category. Six levels of support. A scope agreed before the work begins.',
      proof: { label: 'What we examine', items: [['Legal entity', 'Chinese registration, operating status and company relationships'], ['Certificate & model', 'Holder, validity and the product scope actually covered'], ['Product & field work', 'Specifications, samples and agreed on-site checks']], foot: 'Taiwan × Shenzhen · Client-paid work · No supplier commissions' },
      category: { label: 'One category only', title: 'We specialise in charger and power electronics supply chains.', products: ['Chargers', 'Power adapters', 'Power banks', 'GaN fast chargers', 'Upstream components for these products'], statement: 'ZimonAI combines document checks with category knowledge of product architecture, bills of materials, wattage, certification scope and market costs. This focused approach helps us identify discrepancies between the documents, supplier claims and the product itself.' },
      dossier: { company: 'Lumen Harbor Devices Co., Ltd.', since: '2014', certificate: 'UL certified', factory: 'Shenzhen', run: 'Run demonstration', running: 'Cross-checking records…', done: 'Three claims checked. One discrepancy requires attention.', reset: 'Run again' },
      checks: [['Business registration', 'Entity found', 'verified'], ['Certificate holder', 'Holder differs from supplier', 'discrepancy'], ['Product model scope', 'Model not located in record', 'unresolved']],
      decision: { label: 'When buyers use ZimonAI', title: 'The useful moment is before money, inventory or trust is committed.', lead: 'A verification request starts with a real buying decision—not a generic risk score.', items: [
        ['Before a first order', 'Confirm the Chinese legal entity behind the English trading name and supplier page.', 'Identity, status and registration details'],
        ['Before paying a deposit', 'Check whether a supplied certificate belongs to the same company and covers the quoted model.', 'Holder, status and model scope'],
        ['When documents conflict', 'Put company names, dates, addresses and certificate records side by side.', 'A clear discrepancy trail']
      ] },
      story: { label: 'An investigation, not a score', title: 'A supplier claim is only the first layer.', intro: 'The work moves from the exact claim to the source record, then through relationship checks before a conclusion is written.', steps: [
        { no: '01', title: 'Preserve the exact claim', text: 'We keep the company name, certificate number, model and address as supplied. Small differences are evidence; they are not cleaned away.', stage: 'claim' },
        { no: '02', title: 'Locate a traceable record', text: 'Official registries and issuer-controlled databases come first. Marketplace pages and aggregators may guide a search, but they are not final proof.', stage: 'source' },
        { no: '03', title: 'Test the relationships', text: 'A certificate can be genuine and still belong to another entity or exclude the quoted model. Holder, address, dates and scope must align.', stage: 'compare' },
        { no: '04', title: 'Write only what the evidence supports', text: 'The report separates verified facts, unresolved points and discrepancies. No invented confidence score hides a missing record.', stage: 'result' }
      ] },
      compare: { label: 'Evidence seam', title: 'The claim and the record look similar—until each field is aligned.', hint: 'Drag to compare a fictional supplier claim with the demonstration record.', leftTitle: 'Supplier claim', rightTitle: 'What the record shows', left: ['Established: 2014', 'Certificate holder: Lumen Harbor Devices', 'Model: LH-65W'], right: ['Registered: 2023', 'Certificate holder: Lumen Harbor Trading', 'Model scope: LH-45W only'], conclusion: 'Discrepancy found: entity history, holder name and model scope do not align.' },
      why: { label: 'Why ZimonAI', title: 'A China research desk for buyers who do not have one in-house.', text: 'Chinese legal names, registration records and certification systems rarely line up neatly with an English supplier profile. ZimonAI translates that research into a report the buyer can read, question and use in a purchasing decision.' },
      operating: { label: 'ZimonAI operating record', title: 'Specific by design, small by disclosure.', lead: 'These are operating facts—not invented scale signals.', facts: [
        ['Client side', 'The overseas buyer is the client; ZimonAI does not represent the supplier.'],
        ['Payment independence', 'No supplier commission, sourcing fee, kickback or handled purchase funds.'],
        ['Working footprint', 'Taiwan × Shenzhen coordination; assignment coverage is confirmed case by case.'],
        ['Conclusion system', 'Every checked claim ends as Verified, Unable to Verify or Discrepancy Found.']
      ] },
      service1: { tier: 'Tier 1', title: 'Certificate Verification', price: 'USD 149', unit: 'per standard case', time: '24–48 hours after complete intake', text: 'Legal entity, company status, certificate holder, model scope and cross-record inconsistencies—documented with traceable evidence where available.', mini: ['Company identity', 'Certificate holder', 'Model scope', 'Evidence summary'] },
      service2: { tier: 'Tier 2', title: 'Remote Due Diligence', price: 'USD 349', unit: 'per standard case', time: '3–5 business days after complete intake', text: 'T1 plus address, ownership, litigation, public import/export indicators and manufacturer-versus-trader analysis.', mini: ['Address type', 'Ownership', 'Litigation records', 'Manufacturer identity'] },
      sources: { label: 'Source index', title: 'The source depends on the claim.', lead: 'We choose sources by the exact company, certificate, model and market claim submitted. Availability and public access vary.', items: [
        ['Chinese company records', 'Legal name, unified social credit code, status, establishment date and registered address.'],
        ['CNCA and certification records', 'Certificate existence, status, issuing body and holder where records are available.'],
        ['Issuer-controlled systems', 'Product and model records such as UL Product iQ when relevant to the submitted claim.'],
        ['Market-specific official sources', 'FCC, EU NANDO, Japanese or other official systems when the product claim requires them.']
      ] },
      demoTitle: 'Open a fictional evidence file.', demoLead: 'Choose a claim to see how source, record and result are separated. This is a product demonstration—not a live database search or client case.',
      demoTabs: [
        { id: 'identity', label: 'Company identity', source: 'Official company registry', claim: 'Lumen Harbor Devices Co., Ltd.', record: 'Legal entity located; registration status active.', result: 'verified', note: 'The submitted Chinese legal name matches the located entity.' },
        { id: 'registration', label: 'Business registration', source: 'Official company registry', claim: 'Operating since 2014', record: 'Date of establishment: 18 March 2023.', result: 'discrepancy', note: 'The located registration record does not support the claimed operating history.' },
        { id: 'certificate', label: 'UL certificate', source: 'Certification database', claim: 'Certificate belongs to supplier', record: 'Record located under Lumen Harbor Trading Co., Ltd.', result: 'discrepancy', note: 'A certificate exists, but the holder name does not match the supplier legal entity.' },
        { id: 'model', label: 'Product model', source: 'Certificate model scope', claim: 'LH-65W is covered', record: 'Listed models: LH-30W and LH-45W.', result: 'unresolved', note: 'The submitted model could not be located within the record reviewed.' },
        { id: 'address', label: 'Factory address', source: 'Registration and supplied documents', claim: 'Factory in Shenzhen', record: 'Registered address located; manufacturing activity requires on-site confirmation.', result: 'unresolved', note: 'A registered address alone does not establish factory activity.' }
      ],
      limitsTitle: 'We also tell you what we cannot verify.', limitsText: 'A valid record does not guarantee future behaviour, product quality, shipment conformity or commercial performance. Clear limits are part of the report—not fine print.', finalTitle: 'Have a supplier claim you need checked?', finalText: 'Send the company name, link, certificate or product model. We will tell you what can be checked and which tier fits before work begins.'
    },
    services: {
      kicker: 'T1–T6 services', title: 'Start with the level that matches the decision in front of you.', lead: 'This is one staircase, not six unrelated products. Each higher level adds work to the evidence and access established below it.',
      staircase: { label: 'Choose a level', title: 'Six levels, one continuous verification path.', lead: 'Select a level to see its full scope. Every panel shows what is excluded and whether supplier consent is required.' },
      sampleReport: { label: 'T1 sample report', title: 'Review a complete deliverable before you purchase.', lead: 'This eight-page English sample replaces the supplier name with “XX” and shows the full structure: scope, evidence comparison, risk reasoning, limitations and a pre-contract punchlist. Actual length and content vary with the evidence available.', facts: ['8-page PDF', 'English sample', 'Supplier name de-identified'], open: 'Open the full sample report', download: 'Download PDF' },
      labels: { price: 'Price', timing: 'Timing', mode: 'Mode', important: 'Important', notIncluded: 'Not included', consent: 'Supplier consent', fit: 'Best suited to' },
      catalog: [
        { id: 't1', label: 'T1', title: 'Certificate Verification', englishTitle: 'Certificate Verification', summary: 'Remote identity, business-registration and charger-specific certificate checks.', price: 'USD 149', timing: '24–48 hours after complete intake', mode: 'Remote', purchasable: true, groups: [
          { title: 'Supplier identity and legal status', items: ['Business licence authenticity and unified social credit code', 'Registered capital, establishment date and legal representative', 'Whether the registered business scope genuinely includes manufacturing', 'Current status: active, abnormal, cancelled or revoked', 'Dishonest judgment-debtor records', 'Administrative penalty records'] },
          { title: 'Charger-specific certification review', items: ['Whether the FCC ID exists and matches the quoted model and wattage', 'Whether the UL file is valid in UL Product iQ', 'Whether the issuing laboratory appears on an FCC excluded or transition-period list', 'Reasonableness review of the marked specification and quotation against a dated, like-for-like market sample; unusual prices are questions to investigate, not proof of a false quotation'] }
        ], marketReference: {
          label: 'Public supplier quote observation · checked 31 Aug 2026',
          title: 'A selected current quote sample—not audited manufacturing cost.',
          text: 'Across selected Alibaba, Made-in-China and Global Sources listings, advertised unit prices for non-identical 65W GaN wall chargers were about USD 5.20–10.70 at listed MOQs of 50–500 pieces.',
          limits: 'Freight, tax, Incoterms, custom packaging and evidence behind certification claims were not consistently included or disclosed. Compare port count, plug, protocol, components, certification evidence, packaging, warranty, customisation, volume and delivery terms before treating a quotation as high or low.',
          sources: [
            { label: 'Alibaba · 100+ pieces', href: 'https://www.alibaba.com/product-detail/2025-GaN-Customizing-ETL-FCC-Certificated_1601213471100.html' },
            { label: 'Made-in-China · 500 pieces', href: 'https://langbone.en.made-in-china.com/' },
            { label: 'Global Sources · 50+ pieces', href: 'https://www.globalsources.com/manufacturers/330w-dc-usb-c-gan-charger.html?pageNum=282' }
          ]
        }, delivery: 'A 3–5 page report with a risk rating, issue list and questions to ask before signing.', notIncluded: 'On-site work, telephone interview, capacity assessment or quality inspection.', consent: 'Not required', fit: 'Overseas buyers contacting a Chinese supplier for the first time; typical order value USD 5,000–30,000.' },
        { id: 't2', label: 'T2', title: 'Remote Due Diligence', englishTitle: 'Remote Due Diligence', summary: 'T1 plus ownership, litigation, address and manufacturer-versus-trader analysis.', price: 'USD 349', timing: '3–5 business days after complete intake', mode: 'Remote', purchasable: true, upgrade: 'Everything in T1, plus deeper corporate and public-record research.', groups: [
          { title: 'Added at T2', items: ['Classify the registered address as industrial, commercial or residential', 'Related entities and ownership structure', 'Litigation records in China Judgments Online', 'Import and export record search', 'Assess whether the supplier is a manufacturer or a trader presenting itself as one', 'Compare claims across 1688, Alibaba and the supplier website with registered facts'] }
        ], notIncluded: 'On-site work, direct supplier communication or quality inspection.', consent: 'Not required', fit: 'Buyers who have selected a supplier but still question its authenticity; typical order value USD 30,000–100,000.' },
        { id: 't3', label: 'T3', title: 'Verified Remote Interview', englishTitle: 'Verified Remote Interview', summary: 'T2 plus a structured interview and live video walkthrough.', price: 'USD 449–599', timing: '5–7 business days', mode: 'Remote + live video', upgrade: 'Everything in T2, plus direct, consent-based contact with the supplier.', groups: [
          { title: 'Added at T3', items: ['Structured telephone interview with the supplier contact', 'Request a live video walkthrough of production lines, warehouse and samples', 'Compare spoken statements with documents and public records'] }
        ], note: 'If the supplier refuses video access or avoids a specific question, that fact is itself a verification result. It is recorded in the report and flagged as a risk item.', notIncluded: 'Physical site attendance, mass-production supervision or quality inspection.', consent: 'Written consent required', fit: 'Buyers preparing to sign who cannot travel to China; typical order value USD 50,000–200,000.' },
        { id: 't4', label: 'T4', title: 'On-Site Verification', englishTitle: 'On-Site Verification (Single Visit)', summary: 'T3 plus one factory visit and charger-specific output checks.', price: 'USD 899–1,299', timing: '7–10 business days', mode: 'Remote + one site visit', upgrade: 'Everything in T3, plus one agreed factory visit.', groups: [
          { title: 'On-site verification', items: ['Compare the registered address with the actual operating address', 'Observe site size and equipment', 'Check whether production lines are operating', 'Estimate the number of staff present', 'Inspect samples on site', 'Create photographic and video records throughout the agreed visit'] },
          { title: 'Charger-specific specification check', items: ['Spot-check sample output wattage, interface specification and consistency with product markings'] }
        ], notIncluded: 'Mass-production supervision, full quality inspection, shipment inspection or purchasing on the client’s behalf.', consent: 'Written consent required', fit: 'Buyers who need physical confirmation before signing; typical order value above USD 100,000.' },
        { id: 't5', label: 'T5', title: 'Verification Advisor', englishTitle: 'Verification Advisor — Monthly Retainer', summary: 'Ongoing T1–T3 support and supplier-file monitoring.', price: 'USD 1,500–2,500 / month', timing: 'One-month trial; three-month terms thereafter', mode: 'Ongoing retainer', upgrade: 'An ongoing relationship rather than a single delivery.', groups: [
          { title: 'Monthly coverage', items: ['Submit supplier names throughout the sourcing process and receive a T1–T2 standard response within three business days', 'One T3-level deep remote interview each month', 'Build and maintain tracking files for the buyer’s core long-term suppliers'] }
        ], notIncluded: 'On-site verification, which is priced separately at T4; purchasing decisions; purchasing on the client’s behalf.', consent: 'Depends on the monthly task; written consent is required for T3 interviews', fit: 'Buyers opening new suppliers every month, teams monitoring more than ten suppliers, and cross-border ecommerce sourcing teams.' },
        { id: 't6', label: 'T6', title: 'Full Managed Sourcing Verification', englishTitle: 'Full Managed Sourcing Verification', summary: 'T4 and T5 combined with verification across the sourcing process.', price: 'Project quote from USD 5,000', timing: '4–8 weeks', mode: 'Project', upgrade: 'T4 + T5, with verification support across the purchasing workflow.', groups: [
          { title: 'Managed verification workflow', items: ['Screen a pool of candidate suppliers', 'Lead supplier comparison during the RFQ process', 'Complete final due diligence before contract terms are agreed', 'Carry out a pre-production check after the order', 'Arrange a pre-shipment check when required'] }
        ], notIncluded: 'The client retains the purchasing decision and executes payment. ZimonAI acts as the buyer’s independent sourcing gatekeeper, not as a purchasing agent.', consent: 'Written consent required', fit: 'Large buyers, brands entering China sourcing for the first time, and clients that need the verification workflow managed end to end.' }
      ],
      promises: { label: 'Written into every report', title: 'Three commitments in every report.', lead: 'A verification report is only as valuable as the independence of the person writing it. We therefore put these commitments on the cover.', items: [['We are paid only by the buyer', 'We accept no commission, kickback or introduction fee from a factory. Your service fee is our entire income from the assignment.'], ['Every judgment names its source', 'Each conclusion identifies the database, document or photograph behind it. You can rerun any individual check.'], ['We state what was not checked', 'Every report records the observation date, location and limits. A factory checked in March has not automatically been checked again in September.']] },
      prepare: { label: 'Before we quote', title: 'Send the material already in your buying conversation.', lead: 'You do not need a perfect file. More precise inputs make the scope clearer.', items: ['Supplier trading name and Chinese legal name, if known', 'Supplier website, Alibaba page or other profile link', 'Product name and exact model number', 'Certificate image, number or database link', 'Factory or office address being claimed', 'The decision and deadline the verification needs to support'] },
      tier1: { label: 'Tier 1', title: 'Certificate Verification', price: 'USD 149 / standard case', time: '24–48 hours after complete intake', best: 'For a buyer preparing a first order, deposit or renewed commitment who needs to identify the counterparty and test specific documentary claims.', includes: ['Locate and match one Chinese legal entity', 'Review company status, establishment date and registered address', 'Check up to two certificate or authorisation claims', 'Check one quoted model against available certificate scope', 'Align legal names, dates, addresses, holders and models across records', 'Flag missing evidence and material inconsistencies'], output: 'A 3–5 page structured report with a scope summary, evidence matrix, three-state conclusions, source references and explicit limitations.', sequence: [['1 · Intake', 'Freeze the exact names, numbers, links and claims to be checked.'], ['2 · Source search', 'Locate the most authoritative accessible record for each claim.'], ['3 · Cross-check', 'Compare entity, holder, address, dates and product scope.'], ['4 · Report', 'Pair every conclusion with the record and the limit behind it.']] },
      tier2: { label: 'Tier 2', title: 'Remote Due Diligence', price: 'USD 349 / standard case', time: '3–5 business days after complete intake', best: 'For a buyer who has selected a supplier but needs deeper corporate and public-record analysis before a commercial decision.', includes: ['Everything in the standard T1 scope', 'Review the primary supplier and up to two directly related entities', 'Classify the registered address', 'Review ownership, litigation and public import/export indicators', 'Assess manufacturer-versus-trader identity', 'Compare marketplace and website claims with registered facts'], output: 'A remote due-diligence report that separates located records, cross-record conclusions and unresolved limits.', sequence: [['1 · Intake', 'Freeze the supplier, product and decision in scope.'], ['2 · Corporate research', 'Review relationships, address, litigation and available trade indicators.'], ['3 · Identity analysis', 'Test manufacturer-versus-trader and public claims.'], ['4 · Report', 'Pair every conclusion with its evidence and limit.']] },
      deliverables: { label: 'Report structure', title: 'What a verification report is built to contain.', items: [['Scope', 'The exact company, certificate, model, address and question reviewed.'], ['Identity', 'The Chinese legal entity and located company-record fields.'], ['Evidence matrix', 'Supplier claim beside the source record and query date.'], ['Three-state result', 'Verified, Unable to Verify or Discrepancy Found for each claim.'], ['Source appendix', 'Links, screenshots or source records where appropriate and accessible.'], ['Limits and next step', 'What the evidence cannot establish and what further check may be needed.']] },
      custom: { label: 'Outside the standard tiers', title: 'Other requirements are assessed case by case.', text: 'Work outside T1–T6 is accepted only when its scope, responsible party, price and deliverable can be stated clearly.' },
      notIncluded: { title: 'Confirmed separately when relevant', items: ['Supplier search, screening and recommendations', 'Commercial coordination or negotiation support', 'Order, deposit or payment-handling arrangements', 'Product quality checks, sampling or third-party laboratory work', 'Market-specific standards and acceptance criteria', 'Travel, third-party and other pass-through costs'] },
      pricingNote: 'T1 and T2 use fixed prices for the published standard scope. Work outside that scope is discussed before any supplemental charge. No work starts until the required intake is complete.', ctaTitle: 'Not sure which level fits?', ctaText: 'Use the consultation if the right starting point is unclear, or send the supplier, product and decision you are trying to make before choosing a higher level.'
    },
    methodology: {
      kicker: 'Methodology', title: 'A conclusion should be traceable back to the claim and the record.', lead: 'ZimonAI uses an official-source-first method and stops the conclusion where the available evidence stops.', visualAlt: 'Close-up of transformers, capacitors and heat sinks on a power-supply board', mapTitle: 'Explore the verification path', mapLead: 'Select each step to see what is checked, why it matters, which source type is used and what result can follow.',
      nodes: [
        { id: 'intake', label: 'Supplier claim', check: 'Names, links, certificates, models and stated addresses exactly as submitted.', why: 'Small spelling, entity and model differences can change the result.', source: 'Buyer and supplier materials', results: 'Starting point—not a conclusion' },
        { id: 'registry', label: 'Company registry', check: 'Chinese legal name, unified social credit code, status, establishment date and registered address.', why: 'A trading name or English name may not identify the legal counterparty.', source: 'Official Chinese company records', results: 'Verified / unable to verify / discrepancy' },
        { id: 'certificate', label: 'Certificate record', check: 'Whether a record exists, its status, holder, issuer and available details.', why: 'A certificate image can be altered, expired or associated with another company.', source: 'Official or issuer-controlled certificate databases', results: 'Verified / unable to verify / discrepancy' },
        { id: 'holder', label: 'Holder relationship', check: 'Whether certificate holder, supplier entity and claimed factory are the same or clearly related.', why: 'A genuine certificate does not automatically belong to the company offering the product.', source: 'Cross-record comparison', results: 'Relationship supported / unresolved / mismatch' },
        { id: 'model', label: 'Model scope', check: 'Whether the quoted product model appears within the available certificate scope.', why: 'A certificate may cover only specific models, variants or ratings.', source: 'Certificate schedules and product records', results: 'Covered / not located / excluded' },
        { id: 'crosscheck', label: 'Cross-check', check: 'Names, dates, addresses and model details aligned across all located records.', why: 'Contradictions often appear only when sources are placed side by side.', source: 'Evidence matrix', results: 'Consistent / unresolved / discrepancy' },
        { id: 'report', label: 'Evidence report', check: 'Each conclusion paired with source, query date, evidence and limitation.', why: 'The buyer should be able to understand and challenge the reasoning.', source: 'ZimonAI analysis', results: 'Verified / unable to verify / discrepancy found' }
      ],
      sourceRegistry: { label: 'Source families', title: 'Sources are selected by the claim—not by what is easiest to screenshot.', items: [['Company identity', 'Official Chinese enterprise and credit records', 'Legal existence and status do not guarantee performance.'], ['Chinese certification', 'CNCA, accreditation or issuer-controlled records', 'Availability and public detail differ by scheme.'], ['Product listing', 'UL Product iQ or another issuer-controlled product system', 'A listed certificate may cover only named models and ratings.'], ['Market claim', 'FCC, EU NANDO, Japanese or other official sources', 'Used only when relevant to the submitted market claim.']] },
      sourcesTitle: 'Official-source-first does not mean official-source-only.', sourcesText: 'Supplier documents and third-party sources can provide leads or context. They are labelled according to evidential weight and are never silently upgraded into proof.', statusesTitle: 'Three results, not a black-box score', statusText: ['Verified — located evidence supports the specific statement reviewed.', 'Unable to verify — accessible sources do not support a responsible conclusion.', 'Discrepancy found — the supplier claim and located record conflict in a material field.'], handlingTitle: 'Evidence handling', handlingText: 'Reports identify source type and query date and may include links, screenshots or source records where appropriate. Database access changes, so the report states what was available when the query was made.',
      reportAnatomy: { label: 'Anatomy of a conclusion', title: 'Every result needs five visible parts.', items: [['Claim', 'The supplier wording or document field being tested.'], ['Source', 'The registry, regulator or issuer-controlled system consulted.'], ['Record', 'The field or entry actually located.'], ['Reasoning', 'Why the record supports, fails to support or conflicts with the claim.'], ['Limit', 'What this check still cannot prove.']] }
    },
    scope: {
      kicker: 'Scope and limitations', title: 'Start with the decision. Confirm the service scope next.', lead: 'ZimonAI can support more than record verification. The exact work is agreed according to the supplier, product, market and decision involved.', visualAlt: 'Close-up of a hand holding a multi-port USB power adapter', doTitle: 'Ways ZimonAI can help', doItems: ['Find, screen or recommend suppliers when requested', 'Verify companies, certificates, models and commercial claims', 'Arrange on-site checks according to the assignment', 'Carry out or coordinate product quality checks and appropriate third-party testing', 'Compare evidence and explain material discrepancies', 'Build a case-specific service plan before work begins'], dontTitle: 'What we confirm before starting', dontItems: ['Which supplier, product, model or claim is in scope', 'Whether the work is research, field verification, quality checking or a combination', 'Which standards, samples and acceptance criteria apply to quality work', 'Who performs each part when a qualified third party is needed', 'Fees, third-party costs, timing and deliverables', 'Recommendations and conclusions are not determined by supplier kickbacks'],
      limitsTitle: 'Limits of verification', limits: [['A real company is not a guaranteed supplier', 'Registration can establish legal existence and status; it cannot guarantee future conduct, delivery or solvency.'], ['A genuine certificate is not a blanket product guarantee', 'A record may apply only to a holder, model, rating, site or period. It does not prove every shipped unit conforms.'], ['An address is not automatically a factory', 'A registered or visited address does not by itself establish manufacturing ownership, capacity or product quality.'], ['Records have time and access limits', 'Databases can change, be unavailable or omit information. Conclusions relate to records accessible at the stated query time.'], ['On-site verification is transparent', 'Visits are scheduled and conducted with the supplier’s knowledge and consent. They are not covert investigations.']],
      decisionGuide: { label: 'Choose the right service', title: 'One requirement may combine several types of work.', items: [['Who is the legal counterparty?', 'ZimonAI company verification'], ['Does this certificate belong to this entity and model?', 'ZimonAI certificate verification'], ['What can be confirmed at the stated address?', 'ZimonAI scheduled on-site work'], ['Does this batch meet the agreed specification?', 'ZimonAI quality work or a scoped qualified partner'], ['Does the product meet accredited laboratory requirements?', 'A named qualified laboratory coordinated within the assignment']] },
      accreditationMark: 'ROLES', accreditationTitle: 'Qualified work and clear roles', accreditationText: 'When an assignment requires accredited testing, certification or conformity assessment, the qualified third party and the work it is responsible for are identified before the assignment begins.', ctaTitle: 'Does the assignment include quality work?', ctaText: 'Tell us the product, model, market and acceptance criteria. ZimonAI will confirm what can be handled directly, what requires a qualified third party and how each part will be reported.'
    },
    about: {
      kicker: 'About ZimonAI', title: 'A category specialist for buyers of charger and power electronics.', lead: 'ZimonAI 智蒙灣 operates through Taiwan × Shenzhen coordination. The paying client is the overseas buyer, not the supplier being reviewed.',
      originTitle: 'Why this service exists', originText: 'An overseas buyer may receive an English trading name, a certificate image, a factory address and a polished marketplace page. The difficult part is connecting those claims to Chinese legal names and the right official or issuer-controlled record. ZimonAI exists to do that work clearly.',
      modelTitle: 'Paid by the client. Accountable to the client.', modelText: 'When requested, ZimonAI can help identify suppliers, make recommendations, verify claims and arrange follow-on quality work. Recommendations and findings are not shaped by supplier kickbacks. The exact commercial and delivery scope is confirmed for each assignment.',
      footprintTitle: 'Taiwan × Shenzhen. Two-base coordination.', footprintText: 'Research, buyer communication and execution are coordinated across Taiwan and Shenzhen. Assignments are assessed by their actual scope, timing and delivery conditions rather than a fixed public list of cities.',
      locationsTitle: 'Two offices, with different roles.', locationsLead: 'The Taiwan office handles client communication and project coordination. Shenzhen supports company registration and China-side execution.',
      scaleTitle: 'Clear scope before work begins', scaleText: 'Every requirement is reviewed for the question it needs to answer, the work involved, the timing and the final deliverable. An assignment is accepted only when the method and responsibilities can be stated clearly.',
      record: { title: 'How the service works', items: [['Business scope', 'Supplier search, verification and quality-related support'], ['Primary client', 'Overseas small buyers, e-commerce sellers and importers'], ['Commercial principle', 'Client-paid; recommendations are not based on supplier kickbacks'], ['Research work', 'Chinese company, certificate and product-record research'], ['Field work', 'Assessed by assignment requirements and execution conditions'], ['Report logic', 'Verified / Unable to Verify / Discrepancy Found']] },
      registration: { label: 'Business registration', stamp: 'Registered · Shenzhen', publicExcerpt: 'Full licence', title: 'A registered Shenzhen entity, shown with the limits intact.', lead: 'The details below are taken from the business licence supplied by ZimonAI. The Chinese legal name is reproduced exactly as registered.', fields: { legalName: 'Registered legal name', legalRepresentative: 'Legal representative', entityType: 'Entity type', established: 'Established', registeredAddress: 'Registered & reception address' }, entityType: 'Limited liability company (solely owned by a Hong Kong, Macao or Taiwan natural person)', established: '3 March 2026', imageAlt: 'Complete business licence for the Shenzhen ZimonAI legal entity', caption: 'Complete business licence image supplied and approved for publication by ZimonAI.', disclosure: 'ZimonAI has confirmed that the address shown is both its registered address and customer-reception address. Photographs of the public reception areas appear below.' },
      office: { label: 'Shenzhen reception space', title: 'A real place to meet—not a stock photograph.', lead: 'These photographs show the public reception and meeting areas available to customers at ZimonAI’s registered and reception address.', addressLabel: 'Registered & reception address', disclosure: 'The photographs document the public areas where visitors can be received. They are not presented as private rooms.', photos: { lounge: { alt: 'Public customer lounge at ZimonAI’s Shenzhen reception address', caption: 'Public reception lounge and waiting area' }, meeting: { alt: 'Public meeting area at ZimonAI’s Shenzhen reception address', caption: 'Meeting area available for customer conversations and document review' }, reception: { alt: 'Reception desk at ZimonAI’s Shenzhen reception address', caption: 'Reception desk and entrance area' } } },
      principles: [['Explain the conclusion', 'Show what was checked, where it was checked and what remains unresolved.'], ['Prefer traceable sources', 'Use official or issuer-controlled records first when available.'], ['State the boundary', 'Do not turn absence of evidence into certainty or verification into a guarantee.']],
      ctaTitle: 'Bring one supplier and one decision.', ctaText: 'ZimonAI will first identify which claims can be checked and which service tier fits.'
    },
    request: {
      kicker: 'Discuss a requirement', title: 'Tell us which charger or power electronics supplier you are evaluating.', lead: 'Share the material already in the buying conversation. ZimonAI identifies the appropriate T1–T6 level before confirming scope, price and timing.', visualAlt: 'White power bank beside blue charging cables', honest: 'The form is submitted securely to ZimonAI. Once it is saved, the page gives you a reference number; the saved request remains available even if an alert email is not delivered.', fields: { name: 'Your name', email: 'Your email', company: 'Your company (optional)', supplier: 'Supplier name', url: 'Supplier website / Alibaba URL (optional)', chinese: 'Chinese company name, if known (optional)', product: 'Product', question: 'What do you need to establish?', consent: 'I agree that ZimonAI may use these details to assess and respond to this request.', send: 'Submit requirement', required: 'Required' }, placeholders: { name: 'Alex Morgan', email: 'alex@company.com', company: 'Northline Goods', supplier: 'Supplier trading or legal name', url: 'https://…', chinese: '深圳市…有限公司', product: '65W USB-C charger', question: 'For example: check the legal entity, UL file, 65W model scope and the right T1–T6 starting level.' }, after: 'After submission, keep the reference number. Files can be sent separately by email with that reference in the subject.', status: { validation: 'Complete the required fields and acknowledgement.', submitting: 'Submitting securely…', successTitle: 'Requirement recorded', successBody: 'Your reference is', error: 'The request was not saved. Your entries are still here; please try again or use the direct email option.', rateLimit: 'Too many requests were submitted in a short period. Please wait before trying again.' }, directTitle: 'Prefer to write directly?', directText: 'Include the supplier name, link, product, exact model, certificate number and the decision this work needs to support. Do not send payment-card data or unnecessary identity documents.', responseTitle: 'What happens next', responseSteps: ['ZimonAI identifies the evidence and access the question requires.', 'You receive a proposed T1–T6 level, scope and quote.', 'Work begins only after scope, price and delivery timing are agreed.']
    },
    privacy: { kicker: 'Privacy notice', title: 'A minimal-data website by design.', lead: 'Effective 24 August 2026. This notice explains how information is handled on the ZimonAI website.', sections: [['Website use', 'The public website does not use advertising cookies or cross-site advertising profiles. Standard infrastructure logs may be processed by the hosting provider for security and reliable delivery.'], ['Request form', 'The public request form transmits the business and contact fields you submit over HTTPS and saves them with a reference number so the requirement is not lost if an email alert fails.'], ['Information you email', 'If you contact ZimonAI, the message and attachments are used to assess or deliver the requested service, respond to you and maintain necessary business records. Do not send information that is not needed for the verification request.'], ['Sharing', 'Information is not sold. It may be shared only with service providers needed to communicate or deliver an agreed assignment, when you direct us to do so, or when required by law.'], ['Retention and requests', 'Business correspondence is retained only as reasonably needed for the request, service delivery, records and legal obligations. Contact ZimonAI to ask about access, correction or deletion where applicable.'], ['Contact', 'Privacy questions can be sent to simonlo@zimonai.com.']] }
  },

  'zh-tw': {
    prefix: 'zh-tw', htmlLang: 'zh-Hant', locale: 'zh_TW', short: '繁', name: '繁體中文',
    meta: {
      titles: { home: '充電器與電源電子供應商查核｜ZimonAI 智蒙灣', services: '充電器供應商 T1–T6 服務與價格｜ZimonAI 智蒙灣', methodology: '充電器供應商查核方法｜ZimonAI 智蒙灣', scope: '供應商查核範圍與限制｜ZimonAI 智蒙灣', about: '關於 ZimonAI｜台灣 × 深圳', request: '說明充電器供應商需求｜ZimonAI 智蒙灣', privacy: '隱私聲明｜ZimonAI 智蒙灣' },
      descriptions: { home: 'ZimonAI 協助海外買家查核中國充電器、電源適配器與行動電源供應商，包含企業登記、證書與型號比對、遠端盡調，以及按需求確認的現場與品質工作。', services: '比較 ZimonAI 充電器與電源電子供應商 T1–T6 服務，從遠端證照查核到全流程採購把關。', methodology: '了解 ZimonAI 如何核對中國公司登記、FCC ID、UL 檔案、型號與供應商說法。', scope: '了解充電器供應商查核與品質工作的約定範圍、供應商同意要求與服務限制。', about: 'ZimonAI 專注充電器與電源電子供應鏈，採台灣 × 深圳雙基地協作。', request: '提供充電器、電源適配器、行動電源供應商或證照資料，由 ZimonAI 先確認服務層級。', privacy: 'ZimonAI 如何處理你在洽談供應商服務時主動提供的資料。' }
    },
    nav: { services: '服務', servicesBooking: '服務與預約', methodology: '查核方法', scope: '範圍與限制', about: '關於', knowledge: '查核知識', request: '說明需求', menu: '選單', close: '關閉' },
    ui: { supplierProfile: '供應商資料', claimedSince: '自稱成立年份', certification: '認證說法', factory: '工廠地點', evidencePath: 'ZM／證據路徑', compare: '逐欄比對', registryRecord: '登記／證書紀錄', inScope: '本次查核項目', deliverable: '你會收到什麼', whatWeCheck: '實際查什麼', whyItMatters: '為什麼要查', sourceType: '資料來源', possibleResult: '可能結果', origin: '服務起點', model: '營運模式', footprint: '工作範圍', scale: '承接原則', operatingRecord: '營運資料', suppliedMaterial: '你提供的資料', reviewWork: '我們進行的查核', reportField: '報告欄位', openEvidence: '打開證據' },
    common: { skip: '跳到主要內容', eyebrow: '充電器與電源電子', brandDescriptor: '充電器與電源電子查核', demo: '操作示範・以下為虛構供應商', verified: '資料吻合', unresolved: '暫無法查證', discrepancy: '發現資料不符', pending: '等待查核', source: '資料來源', claim: '供應商說法', record: '查到的紀錄', result: '查核結果', queryDate: '查詢日期', reference: '參考編號', email: '郵件', chinaPhone: '中國電話', taiwanPhone: '台灣電話', whatsapp: 'WhatsApp', wechat: 'WeChat', line: 'LINE ID', linkedin: 'LinkedIn', contact: '說明你的需求', methodology: '查看查核方法', independent: '由客戶付費，不收供應商回扣', footerLine: '找對供應商，查清資料，確認產品。', footerCategory: '充電器與電源電子供應商查核', creditCodeLabel: '統一社會信用代碼', chineseAddressLabel: '中文地址', englishAddressLabel: '英文地址', officesLabel: '辦公地點', shenzhenOffice: '深圳辦公室', shenzhenOfficeRole: '公司登記與中國端執行', taiwanOffice: '台灣辦公室｜新北', taiwanOfficeRole: '客戶聯絡與專案協調', appointmentOnly: '會面採預約制', footerScope: '供應商推薦、資料查核與品質工作，都會在每件案件開始前確認範圍與費用。', privacy: '隱私', language: '語言', top: '回到頂端', current: '目前頁面' },
    home: {
      kicker: '在訂金、訂單與信任交出去之前', title: '找對人，查清楚，再確認產品。', categoryLine: '專查深圳充電器、電源適配器與行動電源供應商；付款前，先把公司與證照查清楚。', lead: 'ZimonAI 專門協助海外買家篩選充電與電源電子供應商，核對公司與證照資料，並依約定執行產品與現場查核。', primary: '說明你的需求', secondary: '先看我們怎麼查', distinction: '只做一個品類，提供六個服務層級；開始前先把範圍說清楚。',
      proof: { label: '我們實際核對什麼', items: [['公司主體', '中文法定名稱、登記狀態與企業關係'], ['證書與型號', '持有人、有效狀態及實際涵蓋範圍'], ['產品與現場', '規格、樣品及雙方確認的現場工作']], foot: '台灣 × 深圳協作 · 只向買家收費 · 不收供應商佣金' },
      category: { label: 'One category only', title: '我們專精充電器與電源電子供應鏈', products: ['充電器 Chargers', '電源適配器 Power adapters', '行動電源 Power banks', 'GaN 快充產品 GaN fast chargers', '上述產品的上游零組件 Upstream components'], statement: 'ZimonAI 不只核對文件，也會結合產品結構、物料、瓦數規格、認證範圍與市場成本進行判讀，找出文件、供應商說法與實際產品之間不容易察覺的差異。' },
      dossier: { company: 'Lumen Harbor Devices Co., Ltd.', since: '2014', certificate: '聲稱通過 UL 認證', factory: '深圳', run: '開始示範查核', running: '正在比對登記與證書紀錄…', done: '三項說法已比對，其中一項出現重要落差。', reset: '重新示範' },
      checks: [['公司登記', '找到相符法律主體', 'verified'], ['證書持有人', '持有人不是這家供應商', 'discrepancy'], ['產品型號', '現有紀錄找不到該型號', 'unresolved']],
      decision: { label: '什麼時候值得先查', title: '真正有用的時點，是在你把錢、貨量或信任交出去以前。', lead: '我們不替供應商打一個抽象分數；每次查核都應該對應一個真實的採購決定。', items: [['第一次下單前', '確認英文商號背後究竟是哪一個中國法律主體。', '公司身分、狀態與成立資料'], ['支付訂金前', '確認證書是不是同一家公司持有，報價型號是否真的在證書範圍內。', '證書持有人、有效狀態與型號'], ['文件互相矛盾時', '把公司名稱、日期、地址、證書與型號逐欄排在一起。', '一條看得懂、能追問的差異紀錄']] },
      story: { label: '查核不是打分，而是把說法拆開', title: '供應商說了什麼，只是第一層。', intro: '先保留原話，再找紀錄、核對關係，最後才寫結論。每一步都要看得見。', steps: [
        { no: '01', title: '先保留供應商原本的說法', text: '公司名、證書號、型號與地址照原樣留下。拼法不一、主體不同、年份對不上，都可能是重要線索，不能先替它修飾。', stage: 'claim' },
        { no: '02', title: '回到能複查的資料來源', text: '優先找官方登記或發證機構控制的資料庫。商家頁面和第三方彙整網站可以提供線索，但不能直接當成證明。', stage: 'source' },
        { no: '03', title: '把公司、證書與型號連起來', text: '證書真的存在，不代表一定屬於報價公司，也不代表涵蓋你要買的型號。持有人、地址、日期與產品範圍必須一一對上。', stage: 'compare' },
        { no: '04', title: '證據到哪裡，結論就寫到哪裡', text: '每一項結果分成資料吻合、暫無法查證或發現資料不符。找不到的內容就直接說找不到，不用假分數掩蓋。', stage: 'result' }
      ] },
      compare: { label: '證據比對線', title: '兩份資料乍看很像，逐欄排在一起才看得出差異。', hint: '拖曳滑桿，比較虛構供應商的說法與示範紀錄。', leftTitle: '供應商提供的說法', rightTitle: '查到的紀錄', left: ['自稱成立：2014 年', '證書持有人：Lumen Harbor Devices', '報價型號：LH-65W'], right: ['登記成立：2023 年', '證書持有人：Lumen Harbor Trading', '證書僅列：LH-45W'], conclusion: '發現資料不符：成立年份、證書持有人與型號範圍都沒有對上。' },
      why: { label: 'ZimonAI 解決的不是搜尋，而是判讀', title: '給沒有中國資料研究人員的小型海外買家。', text: '英文商號、中文法定名稱、公司登記、證書圖片與產品型號，常常散落在不同系統裡。ZimonAI 把它們整理成一份買家看得懂、能追問，也能拿去做採購判斷的查核報告。' },
      operating: { label: 'ZimonAI 的營運事實', title: '規模可以小，資訊不能含糊。', lead: '以下都是目前真實的工作方式，不用虛構團隊、客戶數或認證來撐場面。', facts: [['服務誰', '客戶是海外買家，案件聚焦充電器與電源電子供應鏈。'], ['誰付費', '由客戶付費；不收供應商佣金、回扣，也不經手採購款項。'], ['怎麼協作', '台灣與深圳雙基地協作；實際執行範圍依個案條件確認。'], ['怎麼下結論', '每一項說法只會落在「資料吻合、暫無法查證、發現資料不符」三種結果。']] },
      service1: { tier: 'Tier 1', title: '遠端證照查核', price: 'USD 149', unit: '每件標準案件', time: '資料完整後 24–48 小時', text: '查公司法律主體與狀態、證書持有人、型號範圍，再把各份資料的名稱、日期與地址交叉比對。', mini: ['公司身分', '證書持有人', '產品型號', '證據摘要'] },
      service2: { tier: 'Tier 2', title: '遠端深度盡調', price: 'USD 349', unit: '每件標準案件', time: '資料完整後 3–5 個工作日', text: '在基礎查核上增加地址性質、關聯企業、股權、訴訟與製造商身分判讀。', mini: ['地址性質', '股權關係', '訴訟紀錄', '製造身分'] },
      sources: { label: '資料來源索引', title: '要查哪個資料庫，取決於供應商提出哪一種說法。', lead: '公司、證書、型號與銷售市場不同，能查到的資料也不同。報告會標示實際使用的來源與查詢日期。', items: [['中國企業登記資料', '核對中文法定名稱、統一社會信用代碼、公司狀態、成立日期與登記地址。'], ['CNCA 與相關認證紀錄', '依公開資料查證證書是否存在、狀態、發證機構與持有人。'], ['發證機構控制的產品系統', '例如查核內容涉及 UL 時，視情況查找 UL Product iQ 等產品／型號紀錄。'], ['市場別官方系統', '產品說法涉及特定市場時，才視需要查 FCC、EU NANDO、日本或其他官方資料。']] },
      demoTitle: '打開一份虛構供應商的證據檔案。', demoLead: '點選任一項目，就能看到「供應商怎麼說、我們去哪裡查、紀錄寫什麼、最後怎麼判斷」。以下只是服務介面示範，不是即時連線，也不是客戶案例。',
      demoTabs: [
        { id: 'identity', label: '公司身分', source: '中國官方企業登記資料', claim: 'Lumen Harbor Devices Co., Ltd.', record: '找到對應法律主體，公司狀態正常。', result: 'verified', note: '供應商提供的中文法定名稱與查到的公司主體一致。' },
        { id: 'registration', label: '成立年份', source: '中國官方企業登記資料', claim: '自 2014 年開始營運', record: '登記成立日期：2023 年 3 月 18 日。', result: 'discrepancy', note: '官方登記日期無法支持「2014 年起營運」這項說法。' },
        { id: 'certificate', label: 'UL 證書', source: '發證機構控制的認證資料庫', claim: '這張證書屬於供應商', record: '紀錄持有人：Lumen Harbor Trading Co., Ltd.', result: 'discrepancy', note: '證書紀錄存在，但持有人名稱不是供應商的法律主體。' },
        { id: 'model', label: '產品型號', source: '證書所列產品／型號範圍', claim: 'LH-65W 已列入證書', record: '紀錄只列出 LH-30W 與 LH-45W。', result: 'unresolved', note: '目前查到的紀錄裡沒有 LH-65W，不能把其他型號的證書直接套用。' },
        { id: 'address', label: '工廠地址', source: '公司登記與供應商文件', claim: '深圳自有工廠', record: '找到登記地址；是否在該處製造，仍要靠現場查核。', result: 'unresolved', note: '有一個登記地址，只能證明地址資料存在，不能直接證明工廠活動。' }
      ],
      limitsTitle: '查到真紀錄，也不代表所有風險都消失。', limitsText: '公司存在、證書有效或地址找得到，都不能保證日後履約、產品品質與每批出貨合規。把這些邊界寫清楚，是報告的一部分，不是藏在頁尾的小字。', finalTitle: '手上有一家供應商，卻不知道該先查哪裡？', finalText: '把公司名稱、連結、證書或產品型號寄來。我們會先回覆能查什麼、適合哪個層級，再決定是否開始。'
    },
    services: {
      kicker: 'T1–T6 服務', title: '先選與眼前決策相符的層級。', lead: '這是一道逐級增加的服務階梯，不是六個互不相干的產品。往上一級，就是在前一級的證據與接觸深度上繼續增加。',
      staircase: { label: '先選層級', title: '六個層級，一條連續的查核路徑。', lead: '點選層級即可閱讀完整內容。每一級都清楚列出「不包含」與「供應商同意」，不把重要邊界藏起來。' },
      sampleReport: { label: 'T1 報告範例', title: '先看完整交付內容，再決定是否購買。', lead: '這份 8 頁英文範例以「XX」隱去供應商名稱，完整呈現核查範圍、證據比對、風險判讀、限制與簽約前追問清單。實際頁數與內容會依案件可取得的證據調整。', facts: ['8 頁 PDF', '英文範例', '供應商名稱已去識別'], open: '開啟完整範例報告', download: '下載 PDF' },
      labels: { price: '價格', timing: '時程', mode: '方式', important: '重要說明', notIncluded: '不包含', consent: '供應商同意', fit: '適合' },
      catalog: [
        { id: 't1', label: 'T1', title: '遠端證照查核', englishTitle: 'Certificate Verification', summary: '先查供應商身分、合法性，以及充電類產品最重要的認證資料。', price: 'USD 149', timing: '資料完整後 24–48 小時', mode: '純遠端', purchasable: true, groups: [
          { title: '供應商身分與合法性', items: ['營業執照真偽與統一社會信用代碼', '註冊資本、成立日期與法定代表人', '經營範圍是否確實包含「製造」', '經營狀態：存續、異常、註銷或吊銷', '失信被執行人紀錄', '行政處罰紀錄'] },
          { title: '充電類專屬認證比對', items: ['FCC ID 是否存在，是否對應報價型號與瓦數', 'UL 檔案號是否仍有效（UL Product iQ）', '發證實驗室是否出現在 FCC 除名或過渡期名單', '以有日期、同規格的市場樣本判斷標示規格與報價是否合理；異常價格是需要追查的線索，不等於虛假報價的證明'] }
        ], marketReference: {
          label: '公開供應商報價觀察 · 2026 年 8 月 31 日查詢',
          title: '這是當期公開報價樣本，不是經審計的製造成本。',
          text: '本次選取 Alibaba、Made-in-China 與 Global Sources 的非完全同規格 65W GaN 壁插式充電器；公開單價約為 USD 5.20–10.70，頁面所列 MOQ 約為 50–500 件。',
          limits: '頁面未一致包含或揭露運費、稅費、Incoterms、客製包裝與認證主張的佐證。判斷報價高低前，仍須逐項比對埠數、插腳、協議、用料、認證證據、包裝、保固、客製、數量與交付條件。',
          sources: [
            { label: 'Alibaba · 100 件起', href: 'https://www.alibaba.com/product-detail/2025-GaN-Customizing-ETL-FCC-Certificated_1601213471100.html' },
            { label: 'Made-in-China · 500 件', href: 'https://langbone.en.made-in-china.com/' },
            { label: 'Global Sources · 50 件起', href: 'https://www.globalsources.com/manufacturers/330w-dc-usb-c-gan-charger.html?pageNum=282' }
          ]
        }, delivery: '3–5 頁報告，包含風險評級、疑點清單與簽約前追問清單。', notIncluded: '實地查核、電話訪談、產能判斷、品質檢驗。', consent: '不需要', fit: '首次接觸中國供應商的海外買家；常見單筆採購金額 USD 5,000–30,000。' },
        { id: 't2', label: 'T2', title: '遠端深度盡調', englishTitle: 'Remote Due Diligence', summary: '在 T1 基礎上，再查地址性質、股權、訴訟與真實製造身分。', price: 'USD 349', timing: '資料完整後 3–5 個工作日', mode: '純遠端', purchasable: true, upgrade: '包含 T1 全部項目，再增加企業關係與公開紀錄的深度查核。', groups: [
          { title: 'T2 新增項目', items: ['判斷註冊地址屬於工業區、商業區或住宅', '關聯企業與股權結構', '裁判文書網可查的法律訴訟紀錄', '進出口紀錄查詢', '判斷對方是製造商，還是把自己包裝成製造商的貿易商', '比對 1688、阿里巴巴與官網說法是否符合登記事實'] }
        ], notIncluded: '實地查核、直接與供應商溝通、品質檢驗。', consent: '不需要', fit: '已鎖定供應商、但仍對其真實性存疑的買家；常見單筆採購金額 USD 30,000–100,000。' },
        { id: 't3', label: 'T3', title: '電話與視訊訪查', englishTitle: 'Verified Remote Interview', summary: '在 T2 基礎上，直接訪談供應商並進行即時視訊看廠。', price: 'USD 449–599', timing: '5–7 個工作日', mode: '遠端＋視訊', upgrade: '包含 T2 全部項目，再增加供應商知情同意下的直接訪查。', groups: [
          { title: 'T3 新增項目', items: ['與供應商業務窗口進行結構化電話訪談', '要求視訊看廠，直播查看產線、倉庫與樣品', '核對供應商口頭陳述是否符合文件與公開資訊'] }
        ], note: '如果供應商拒絕配合視訊，或刻意迴避特定問題，這個反應本身就是查核結果；報告會如實記錄，並列為風險項。', notIncluded: '實地到場、量產監督、品質檢驗。', consent: '需要書面同意', fit: '準備簽約、但無法親自到中國的買家；常見單筆採購金額 USD 50,000–200,000。' },
        { id: 't4', label: 'T4', title: '單次實地查核', englishTitle: 'On-Site Verification (Single Visit)', summary: '在 T3 基礎上，到廠查核一次，並抽測充電產品的關鍵規格。', price: 'USD 899–1,299', timing: '7–10 個工作日', mode: '遠端＋一次實地', upgrade: '包含 T3 全部項目，再增加一次雙方同意的到廠查核。', groups: [
          { title: '到廠查核', items: ['核對註冊地址與實際經營地址是否一致', '查看廠房規模與設備', '確認產線是否正在運轉', '概估現場員工人數', '現場檢視樣品', '依約定範圍全程拍照與影像存證'] },
          { title: '充電類專屬規格實測', items: ['現場抽測樣品輸出瓦數、介面規格與產品標示是否一致'] }
        ], notIncluded: '量產監督、完整品質檢驗、驗貨、代客採購。', consent: '需要書面同意', fit: '簽約前需要實地確認的買家；常見單筆採購金額 USD 100,000 以上。' },
        { id: 't5', label: 'T5', title: '供應商查核顧問', englishTitle: 'Verification Advisor — Monthly Retainer', summary: '持續提供 T1–T3 支援，並替核心供應商建立追蹤檔案。', price: 'USD 1,500–2,500／月', timing: '首月可單月試用；第二個月起每期三個月', mode: '月費顧問', upgrade: '不是單次交付，而是一段持續協作關係。', groups: [
          { title: '每月服務內容', items: ['採購過程中可隨時提交供應商名稱，依 T1–T2 標準在三個工作日內回覆', '每月包含一次 T3 等級的深度訪查', '為長期合作的核心供應商建立並維護追蹤檔案'] }
        ], notIncluded: '實地查核（需另加 T4 費用）、採購決策、代客採購。', consent: '依當月工作內容而定；進行 T3 訪查時需要書面同意', fit: '每月都要開發新供應商的買家、手上有十家以上供應商要持續監控的買家，以及跨境電商採購團隊。' },
        { id: 't6', label: 'T6', title: '全託管採購把關', englishTitle: 'Full Managed Sourcing Verification', summary: '整合 T4 與 T5，把查核放進整段採購流程。', price: '專案報價，USD 5,000 起', timing: '4–8 週', mode: '專案制', upgrade: '整合 T4＋T5，並把查核工作延伸到採購流程各階段。', groups: [
          { title: '全流程把關', items: ['從候選供應商池進行篩選', '主導 RFQ 過程中的供應商比對', '在合約條款確定前完成最終盡調', '下單後進行量產前查核', '必要時安排裝運前查核'] }
        ], notIncluded: '採購決策與付款執行仍由客戶負責。ZimonAI 是買家的獨立採購把關人，不是採購代理。', consent: '需要書面同意', fit: '大型買家、第一次進入中國採購市場的品牌，以及需要把整套採購把關流程交由專人管理的客戶。' }
      ],
      promises: { label: '寫進每一份報告', title: '寫進每一份報告的三項承諾', lead: '一份查核報告的價值，等於撰寫者獨立性的價值。所以我們每一次都把這件事寫在封面。', items: [['我們只收買家的錢', '不收工廠任何形式的佣金、回扣或介紹費。你付的服務費，是我們在這件案子上的全部收入。'], ['每一項判斷都標明來源', '每一項結論都附上它的資料庫、文件或照片來源。你可以自己重跑任何一項查核。'], ['我們寫清楚沒查什麼', '每份報告都標明觀察日期、地點與範圍限制。三月查核過的工廠，不等於九月也查核過。']] },
      prepare: { label: '詢價前可以先準備', title: '把採購對話裡已經出現的資料交給我們。', lead: '資料不必整理得很漂亮，但名稱、號碼與型號越精確，越容易判斷能不能查。', items: ['供應商使用的英文商號與中文法定名稱（如已知）', '官方網站、Alibaba 頁面或其他供應商連結', '產品名稱與完整型號', '證書圖片、證書號碼或資料庫連結', '供應商聲稱的工廠／辦公地址', '這次查核要支援的決定與期限'] },
      tier1: { label: 'Tier 1', title: '遠端證照查核', price: 'USD 149／每件標準案件', time: '資料完整後 24–48 小時', best: '適合第一次下單、準備付訂金，或隔一段時間重新合作前，想先確認交易主體與文件說法的海外買家。', includes: ['核對一個中國法律主體', '查公司狀態、成立日期與登記地址', '核對最多兩項證書或認證主張', '核對一個報價型號是否在證書範圍', '把公司名、日期、地址、持有人與型號逐欄比對', '標出找不到的證據與會影響判斷的資料落差'], output: '一份 3–5 頁結構化報告，包含本次範圍、證據比對、三種查核結果、來源紀錄與限制。', sequence: [['1・收件', '先固定這次要查的名稱、號碼、連結與供應商說法。'], ['2・找紀錄', '依每項說法找到當下可取得、可信度最高的資料來源。'], ['3・交叉比對', '核對主體、持有人、地址、日期與產品範圍。'], ['4・寫報告', '每一個結論都要能回到紀錄，也要附上限制。']] },
      tier2: { label: 'Tier 2', title: '遠端深度盡調', price: 'USD 349／每件標準案件', time: '資料完整後 3–5 個工作日', best: '適合已經鎖定供應商，但希望在商業決定前進一步查清企業背景與公開說法的買家。', includes: ['包含標準 T1 全部項目', '一家主要供應商與最多兩家直接關聯企業', '判讀登記地址性質', '查股權、訴訟與公開進出口線索', '判讀製造商或貿易商身分', '比對平台、官網說法與登記事實'], output: '一份把企業關係、公開紀錄、判讀依據與未解限制分開列出的遠端盡調報告。', sequence: [['1・收件', '固定供應商、產品與本次決定。'], ['2・深挖紀錄', '查企業關係、地址、訴訟與可取得的進出口線索。'], ['3・身分判讀', '比對製造商／貿易商身分與公開說法。'], ['4・寫入報告', '逐項列出依據與限制。']] },
      deliverables: { label: '報告內容', title: '一份查核報告，至少要讓你看見這六個部分。', items: [['查核範圍', '這次究竟查哪家公司、哪張證書、哪個型號、哪個地址。'], ['公司身分', '查到的中文法律主體，以及公司登記中的重要欄位。'], ['證據比對表', '供應商說法、資料來源、查詢日期與紀錄內容並排。'], ['逐項結果', '每項分別標成資料吻合、暫無法查證或發現資料不符。'], ['來源附件', '在適當且可取得時，附上連結、截圖或來源紀錄。'], ['限制與下一步', '這次仍不能證明什麼，以及是否需要現場查核、驗貨或其他專業服務。']] },
      custom: { label: '標準服務之外', title: '其他需求，先逐案確認。', text: 'T1–T6 以外的工作會另行評估；只有在範圍、執行者、費用與交付內容都能說清楚時才接受。' },
      notIncluded: { title: '有需要時另行確認', items: ['供應商搜尋、初篩與推薦', '商業協調或議價協助', '訂單、訂金或付款處理方式', '品質檢測、抽樣與第三方實驗室工作', '特定市場標準與驗收條件', '差旅、第三方或其他代墊成本'] },
      pricingNote: 'T1 與 T2 依公開標準範圍固定收費；超出範圍的工作會先說明，再由你決定是否接受補充報價。必要資料未完整以前，不會開始計算交付時間。', ctaTitle: '不知道該選哪一個層級？', ctaText: '如果不確定從哪裡開始，可以先預約諮詢；較高層級仍可先提供供應商、產品與你正要做的決定。'
    },
    methodology: {
      kicker: '查核方法', title: '每一個結論，都要能沿路回到原始說法與資料來源。', lead: '我們優先找官方或發證機構控制的資料；查不到的地方就停下來，不把推測寫成事實。', visualAlt: '電源板上的變壓器、電容與散熱片近拍', mapTitle: '走一遍完整查核路徑', mapLead: '點選每一步，查看實際查什麼、為什麼要查、會用哪類資料，以及最後可能得到什麼結果。',
      nodes: [
        { id: 'intake', label: '供應商說法', check: '照原樣保留公司名、連結、證書、型號與地址。', why: '一個字、不同主體或型號尾碼，都可能讓結果完全不同。', source: '買家與供應商提供的資料', results: '只是起點，還不是結論' },
        { id: 'registry', label: '公司登記', check: '中文法定名稱、統一社會信用代碼、公司狀態、成立日期與登記地址。', why: '英文商號或店鋪名稱，不一定就是實際收款與簽約的法律主體。', source: '中國官方企業登記／信用資料', results: '資料吻合／暫無法查證／資料不符' },
        { id: 'certificate', label: '證書紀錄', check: '證書是否存在、目前狀態、持有人、發證方與公開細節。', why: '供應商傳來的證書圖片可能已過期、遭修改，或原本就屬於別家公司。', source: '官方或發證機構控制的認證資料庫', results: '資料吻合／暫無法查證／資料不符' },
        { id: 'holder', label: '持有人關係', check: '證書持有人、供應商主體與聲稱的工廠是不是同一方，或是否有可說明的關係。', why: '證書是真的，不代表報價公司有權使用。', source: '公司與證書紀錄交叉比對', results: '關係成立／關係不明／主體不符' },
        { id: 'model', label: '產品型號', check: '報價的完整型號是否列在公開可查的證書產品範圍內。', why: '同一張證書通常只涵蓋特定型號、版本或額定規格。', source: '證書附表與產品資料', results: '有列入／目前找不到／明確排除' },
        { id: 'crosscheck', label: '逐欄比對', check: '把不同紀錄裡的公司名、日期、地址、持有人與型號排在一起。', why: '很多矛盾只有並排之後才看得出來。', source: 'ZimonAI 證據比對表', results: '一致／仍有缺口／發現資料不符' },
        { id: 'report', label: '查核報告', check: '每項結論都附上資料來源、查詢日期、證據內容與限制。', why: '買家應該看得懂我們為什麼這樣判斷，也能針對某一項追問。', source: 'ZimonAI 查核與判讀', results: '資料吻合／暫無法查證／發現資料不符' }
      ],
      sourceRegistry: { label: '資料來源類型', title: '不是哪個網站方便就查哪個，而是先看要證明哪一件事。', items: [['公司身分', '中國官方企業登記與信用資料', '能查法律存在與狀態，不能保證履約。'], ['中國認證', 'CNCA、認可資料或發證機構系統', '不同制度公開的欄位與可查程度不同。'], ['產品與型號', 'UL Product iQ 或其他發證方控制的產品系統', '證書可能只適用特定型號與額定規格。'], ['特定市場說法', 'FCC、EU NANDO、日本或其他官方系統', '只有在供應商提出相關市場說法時才查。']] },
      sourcesTitle: '官方來源優先，不代表只看官方來源。', sourcesText: '供應商文件與第三方資料可以協助找到線索或補充背景，但報告會標示它們的證據分量，不會悄悄把一張網頁截圖升級成官方證明。', statusesTitle: '不用黑箱分數，只保留三種看得懂的結果', statusText: ['資料吻合：查到的證據支持這一項具體說法。', '暫無法查證：目前能取得的資料不足，不能負責任地下結論。', '發現資料不符：供應商說法與查到的紀錄，在重要欄位互相矛盾。'], handlingTitle: '證據怎麼保留', handlingText: '報告會標出資料來源與查詢日期，並在適當情況附上連結、截圖或來源紀錄。資料庫可能改版、暫停或調整公開內容，因此結論只對當次實際查到的資料負責。',
      reportAnatomy: { label: '一項結論的五個部分', title: '只有結果不夠，還要看得懂它怎麼來。', items: [['供應商說法', '這次要驗證的原話、文件欄位或產品說明。'], ['資料來源', '實際查詢的登記系統、監管機關或發證機構資料庫。'], ['查到的紀錄', '資料庫裡真正出現的公司、日期、持有人或型號。'], ['判讀理由', '為什麼這份紀錄支持、不足以支持，或直接推翻供應商說法。'], ['查核限制', '即使這一項成立，仍然不能證明哪些事情。']] }
    },
    scope: {
      kicker: '服務範圍', title: '先說你要做什麼決定，再確認服務怎麼組合。', lead: 'ZimonAI 能協助的不只是資料查核。實際工作會依供應商、產品、市場與客戶決策另行確認。', visualAlt: '手持多埠 USB 電源適配器的近拍', doTitle: 'ZimonAI 可以怎麼協助', doItems: ['依需求搜尋、初篩或推薦供應商', '查核公司、證書、型號與商業說法', '依個案需求安排現場確認', '執行或協調產品品質檢測與適當的第三方測試', '把不同證據排在一起，說明關鍵落差', '開始前先整理成一份符合個案的服務方案'], dontTitle: '開始前會先確認', dontItems: ['這次要處理的供應商、產品、型號或具體說法', '工作屬於資料研究、現場確認、品質檢測，還是多項組合', '品質工作要用的標準、樣品與驗收條件', '需要合格第三方時，每一部分由誰執行', '費用、第三方成本、時程與交付內容', '供應商回扣不會成為推薦或結論的依據'],
      limitsTitle: '查核有這些邊界', limits: [['公司是真的，不等於交易一定可靠', '登記資料能確認法律主體與當下狀態，不能保證未來交付、履約或償付能力。'], ['證書是真的，不等於所有產品都合規', '證書可能只適用特定持有人、型號、額定規格、地點或期間，也不能證明每一件出貨品。'], ['地址存在，不等於一定是自有工廠', '登記地址或到訪地址本身，不能證明工廠所有權、產能與產品品質。'], ['資料庫有時間與存取限制', '公開資料可能改版、暫停或省略欄位；報告只針對標示查詢日期時可取得的內容。'], ['現場查核是公開透明的', '到訪會先預約，並在供應商知情同意下進行；不是秘密調查。']],
      decisionGuide: { label: '先選對服務', title: '同一個需求，可能會組合幾種工作。', items: [['實際簽約與收款的是哪一家公司？', 'ZimonAI 公司資料查核'], ['這張證書是否屬於該公司並涵蓋這個型號？', 'ZimonAI 證書與型號查核'], ['對外提供的地址現場能確認什麼？', 'ZimonAI 預約現場工作'], ['這批貨是否符合約定規格？', 'ZimonAI 品質工作或納入方案的合格協作方'], ['產品是否符合認可實驗室要求？', '在案件中明確指定的合格實驗室']] },
      accreditationMark: '分工', accreditationTitle: '需要合格第三方時，先把分工說清楚', accreditationText: '案件需要認可測試、認證或符合性評估時，會在開始前確認合格第三方，以及它實際負責的工作範圍。', ctaTitle: '需求包含品質工作嗎？', ctaText: '請提供產品、型號、目標市場與驗收條件。ZimonAI 會確認哪些可直接執行、哪些需要合格第三方，並事先說明報告方式。'
    },
    about: {
      kicker: '關於 ZimonAI', title: '專注充電器與電源電子供應鏈，不把自己包裝成什麼都懂。', lead: 'ZimonAI 智蒙灣採台灣 × 深圳雙基地協作。付費客戶是海外買家，不是被查核的供應商。',
      originTitle: '為什麼會有這項服務', originText: '海外買家手上常有英文商號、證書圖片、工廠地址與看似完整的供應商頁面。真正困難的是：找出對應的中文法律主體，進入正確的資料庫，再判斷這幾份資料能不能互相對上。ZimonAI 就是把這段工作做清楚。',
      modelTitle: '由客戶付費，也對客戶負責', modelText: '客戶有需求時，ZimonAI 可以協助找供應商、提供推薦、查核資料，並安排後續品質工作。推薦與查核結論不以供應商回扣為依據；每一件的商業與交付範圍都會另行確認。',
      footprintTitle: '台灣 × 深圳，雙基地協作', footprintText: '從資料研究、買家溝通到現場執行，工作由台灣與深圳兩地協作。實際可承接範圍依需求、時間與執行條件確認，不在網站上先劃定城市名單。',
      locationsTitle: '兩個辦公地點，各自負責不同工作。', locationsLead: '台灣辦公室負責客戶聯絡與專案協調；深圳辦公室支援公司登記與中國端執行。',
      scaleTitle: '開始工作以前，先把範圍與交付說清楚', scaleText: '每一件需求都會先確認要解決的問題、工作範圍、時程與交付方式。只有在方法和責任都能說清楚的情況下，才會正式承接。',
      record: { title: '服務方式與工作內容', items: [['業務範圍', '供應商搜尋、資料查核與品質相關協助'], ['主要客戶', '海外小型買家、電商賣家與進口商'], ['商業原則', '由客戶付費，推薦不以供應商回扣為依據'], ['研究工作', '查中國公司、證書與產品／型號紀錄'], ['現場工作', '依個案需求與執行條件確認'], ['報告結果', '資料吻合／暫無法查證／發現資料不符']] },
      registration: { label: '企業登記資料', stamp: '深圳登記主體', publicExcerpt: '完整執照', title: '不只是一個網站品牌：ZimonAI 在深圳有實際登記主體。', lead: '以下內容來自 ZimonAI 提供的營業執照；公司法定名稱與註冊地址照執照原文呈現。', fields: { legalName: '登記法定名稱', legalRepresentative: '法定代表人', entityType: '企業類型', established: '成立日期', registeredAddress: '註冊暨實際接待地址' }, entityType: '有限責任公司（港澳台自然人獨資）', established: '2026 年 3 月 3 日', imageAlt: '深圳智蒙灣登記主體的完整營業執照', caption: '由 ZimonAI 提供並確認公開的完整營業執照影像。', disclosure: '經 ZimonAI 確認，執照上的地址同時是公司註冊地址與實際接待地址；下方列出公共接待區實景。' },
      office: { label: '深圳實際接待空間', title: '是可以坐下來見面的地方，不是素材庫照片。', lead: '以下是 ZimonAI 註冊暨實際接待地址內，顧客可使用的公共接待區與會議區。', addressLabel: '註冊暨實際接待地址', disclosure: '照片只呈現顧客實際可使用的公共接待與會議區域。', photos: { lounge: { alt: 'ZimonAI 深圳接待地址的公共顧客休息區', caption: '公共接待休息區與等候空間' }, meeting: { alt: 'ZimonAI 深圳接待地址的公共會議區', caption: '可進行顧客溝通與文件討論的公共會議區' }, reception: { alt: 'ZimonAI 深圳接待地址的接待前台', caption: '接待前台與出入區域' } } },
      principles: [['把結論說明白', '交代查了什麼、去哪裡查，以及還有哪些問題沒有答案。'], ['先找可追溯的紀錄', '能查官方或發證機構資料時，不拿第三方彙整頁當最終證明。'], ['邊界也要寫進報告', '缺乏證據就是缺乏證據，查核結果也不等於對未來的保證。']], ctaTitle: '帶來一家供應商，以及你正要做的決定。', ctaText: '我們先確認哪些說法查得到、應該使用哪一個服務層級。'
    },
    request: {
      kicker: '說明服務需求', title: '告訴我們，你正在評估哪一家充電或電源電子供應商。', lead: '把採購對話裡已經有的資料送來。ZimonAI 會先判斷適合哪個層級，再回覆範圍、價格與時間。', visualAlt: '白色行動電源與藍色充電線', honest: '表單會安全傳送到 ZimonAI。成功保存後，頁面會顯示需求編號；即使通知信未能送達，已保存的需求仍會保留。', fields: { name: '你的姓名', email: '你的 Email', company: '公司名稱（選填）', supplier: '供應商名稱', url: '供應商網站／Alibaba 連結（選填）', chinese: '中文法定名稱，如已知（選填）', product: '產品與型號', question: '你現在最想查清楚什麼？', consent: '我同意 ZimonAI 使用以上資料評估並回覆這項需求。', send: '送出需求', required: '必填' }, placeholders: { name: '林先生', email: 'name@company.com', company: 'Northline Goods', supplier: '英文商號或中文法定名稱', url: 'https://…', chinese: '深圳市…有限公司', product: '65W USB-C 充電器，型號 X65', question: '例如：確認公司主體、UL 檔案、65W 型號範圍，以及適合從 T1–T6 哪一級開始。' }, after: '送出後請保留需求編號；證書、報價單或供應商文件可另寄 Email，並在主旨註明該編號。', status: { validation: '請完成必填欄位並勾選同意。', submitting: '正在安全送出…', successTitle: '需求已保存', successBody: '你的需求編號是', error: '這次沒有成功保存；你填的內容仍在頁面上，請稍後再試或改用右側 Email 聯絡。', rateLimit: '短時間內送出的次數過多，請稍後再試。' }, directTitle: '也可以直接寫 Email', directText: '請附上供應商名稱、連結、產品完整型號、證書號碼，以及這次查核要支援的決定。不要傳送信用卡資訊或查核不需要的身分文件。', responseTitle: '送出後的流程', responseSteps: ['先判斷你的問題需要哪些資料與接觸深度。', '回覆適合的 T1–T6 層級、範圍與報價。', '你確認範圍、價格與交付時間後，才開始工作。']
    },
    privacy: { kicker: '隱私聲明', title: '網站刻意少收資料。', lead: '生效日期：2026 年 8 月 24 日。以下說明 ZimonAI 網站如何處理你主動提供的資訊。', sections: [['瀏覽網站', '公開網站不使用廣告 Cookie，也不建立跨網站廣告檔案。託管服務商可能為了資安與穩定傳輸處理基本系統紀錄。'], ['需求表單', '公開需求表單會透過 HTTPS 傳送你送出的聯絡與業務資料，並以需求編號保存；即使通知 Email 交寄失敗，需求本身也不會因此遺失。'], ['你寄來的內容', 'ZimonAI 會使用信件與附件評估需求、執行雙方同意的服務、回覆問題，以及保存必要的商業紀錄。請勿提供查核不需要的資料。'], ['資料分享', 'ZimonAI 不會出售你的資料。只有在完成雙方同意的工作確有需要、你指示分享，或法律要求時，才可能提供給必要服務商或相關方。'], ['保存與權利', '商業往來只在處理需求、交付服務、保存紀錄與履行法律義務的合理期間內保存。你可以依法詢問存取、更正或刪除。'], ['聯絡方式', '隱私問題請寄至 simonlo@zimonai.com。']] }
  },

  'zh-cn': {
    prefix: 'zh-cn', htmlLang: 'zh-Hans', locale: 'zh_CN', short: '简', name: '简体中文',
    meta: {
      titles: { home: '充电器与电源电子供应商核查｜ZimonAI 智蒙灣', services: '充电器供应商 T1–T6 服务与价格｜ZimonAI 智蒙灣', methodology: '充电器供应商核查方法｜ZimonAI 智蒙灣', scope: '供应商核查范围与限制｜ZimonAI 智蒙灣', about: '关于 ZimonAI｜台湾 × 深圳', request: '说明充电器供应商需求｜ZimonAI 智蒙灣', privacy: '隐私声明｜ZimonAI 智蒙灣' },
      descriptions: { home: 'ZimonAI 帮助海外买家核查中国充电器、电源适配器与移动电源供应商，包括企业登记、证书与型号比对、远程尽调，以及按需求确认的现场与质量工作。', services: '比较 ZimonAI 充电器与电源电子供应商 T1–T6 服务，从远程证照核查到采购全流程把关。', methodology: '了解 ZimonAI 如何核对中国企业登记、FCC ID、UL 档案、型号与供应商说法。', scope: '了解充电器供应商核查与质量工作的约定范围、供应商同意要求与服务限制。', about: 'ZimonAI 专注充电器与电源电子供应链，采用台湾 × 深圳双基地协作。', request: '提交充电器、电源适配器、移动电源供应商或证照资料，由 ZimonAI 先确认服务层级。', privacy: 'ZimonAI 如何处理你在咨询供应商服务时主动提供的信息。' }
    },
    nav: { services: '服务', servicesBooking: '服务与预约', methodology: '核查方法', scope: '范围与限制', about: '关于', knowledge: '核查知识', request: '说明需求', menu: '菜单', close: '关闭' },
    ui: { supplierProfile: '供应商资料', claimedSince: '自称成立年份', certification: '认证说法', factory: '工厂地点', evidencePath: 'ZM／证据路径', compare: '逐项比对', registryRecord: '登记／证书记录', inScope: '本次核查内容', deliverable: '你会收到什么', whatWeCheck: '具体核查什么', whyItMatters: '为什么要查', sourceType: '信息来源', possibleResult: '可能结果', origin: '服务起点', model: '业务模式', footprint: '执行范围', scale: '承接原则', operatingRecord: '运营资料', suppliedMaterial: '你提交的资料', reviewWork: '我们进行的核查', reportField: '报告字段', openEvidence: '查看证据' },
    common: { skip: '跳到主要内容', eyebrow: '充电器与电源电子', brandDescriptor: '充电器与电源电子核查', demo: '操作演示・以下为虚构供应商', verified: '信息一致', unresolved: '暂时无法核实', discrepancy: '发现信息不一致', pending: '等待核查', source: '信息来源', claim: '供应商说法', record: '查到的记录', result: '核查结果', queryDate: '查询日期', reference: '参考编号', email: '邮箱', chinaPhone: '中国电话', taiwanPhone: '台湾电话', whatsapp: 'WhatsApp', wechat: 'WeChat', line: 'LINE ID', linkedin: 'LinkedIn', contact: '说明你的需求', methodology: '查看核查方法', independent: '由客户付费，不收供应商回扣', footerLine: '找对供应商，查清资料，确认产品。', footerCategory: '充电器与电源电子供应商核查', creditCodeLabel: '统一社会信用代码', chineseAddressLabel: '中文地址', englishAddressLabel: '英文地址', officesLabel: '办公地点', shenzhenOffice: '深圳办公室', shenzhenOfficeRole: '公司登记与中国端执行', taiwanOffice: '台湾办公室｜新北', taiwanOfficeRole: '客户联络与项目协调', appointmentOnly: '会面采用预约制', footerScope: '供应商推荐、资料核查与质量工作，都会在每个项目开始前确认范围与费用。', privacy: '隐私', language: '语言', top: '返回顶部', current: '当前页面' },
    home: {
      kicker: '在订金、订单和信任交出去之前', title: '找对人，查清楚，再确认产品。', categoryLine: '专查深圳充电器、电源适配器与移动电源供应商；付款前，先把企业与证照查清楚。', lead: 'ZimonAI 专门帮助海外买家筛选充电与电源电子供应商，核对企业与证照资料，并按约定执行产品和现场核查。', primary: '说明你的需求', secondary: '先看我们怎么查', distinction: '只做一个品类，提供六个服务层级；开始前先把范围说清楚。',
      proof: { label: '我们实际核对什么', items: [['公司主体', '中文法定名称、登记状态与企业关系'], ['证书与型号', '持有人、有效状态及实际覆盖范围'], ['产品与现场', '规格、样品及双方确认的现场工作']], foot: '台湾 × 深圳协作 · 只向买家收费 · 不收供应商佣金' },
      category: { label: 'One category only', title: '我们专注充电器与电源电子供应链', products: ['充电器 Chargers', '电源适配器 Power adapters', '移动电源 Power banks', 'GaN 快充产品 GaN fast chargers', '上述产品的上游零部件 Upstream components'], statement: 'ZimonAI 不只核对文件，也会结合产品结构、物料、功率规格、认证范围与市场成本进行判断，找出文件、供应商说法与实际产品之间不易察觉的差异。' },
      dossier: { company: 'Lumen Harbor Devices Co., Ltd.', since: '2014', certificate: '声称通过 UL 认证', factory: '深圳', run: '开始演示核查', running: '正在比对登记与证书记录…', done: '三项说法已完成比对，其中一项存在重要差异。', reset: '重新演示' },
      checks: [['企业登记', '找到对应法律主体', 'verified'], ['证书持有人', '持有人不是这家供应商', 'discrepancy'], ['产品型号', '现有记录中没有该型号', 'unresolved']],
      decision: { label: '什么时候值得先查', title: '真正有用的时间点，是在你把钱、货量或信任交出去以前。', lead: '我们不替供应商打一个含糊的风险分数；每次核查都应该对应一个真实的采购决定。', items: [['第一次下单前', '确认英文商号背后究竟是哪一个中国法律主体。', '企业身份、状态和成立信息'], ['支付订金前', '确认所交证书是否属于同一家公司，报价型号是否在证书范围内。', '证书持有人、有效状态和型号'], ['文件互相矛盾时', '把公司名称、日期、地址、证书和型号逐项放在一起比较。', '一条清楚、可以继续追问的差异记录']] },
      story: { label: '核查不是打分，而是把说法拆开', title: '供应商说了什么，只是第一层。', intro: '先保留原话，再找记录、核对关系，最后才下结论。整个过程应该看得见。', steps: [
        { no: '01', title: '先保留供应商原本的说法', text: '公司名、证书号、型号和地址按原样留下。拼写不同、主体不同、年份对不上，都可能是重要线索，不能先替供应商修正。', stage: 'claim' },
        { no: '02', title: '回到能够复查的信息源', text: '优先查官方登记或发证机构控制的数据库。店铺页面和第三方汇总网站可以提供线索，但不能直接当成证明。', stage: 'source' },
        { no: '03', title: '把公司、证书和型号连起来', text: '证书真实存在，不代表一定属于报价公司，也不代表覆盖你要买的型号。持有人、地址、日期和产品范围需要逐项对上。', stage: 'compare' },
        { no: '04', title: '证据到哪里，结论就写到哪里', text: '每一项结果分为信息一致、暂时无法核实或发现信息不一致。查不到的内容就直接说查不到，不用假分数掩盖缺口。', stage: 'result' }
      ] },
      compare: { label: '证据比对线', title: '两份资料看起来很像，逐项放在一起才看得出差异。', hint: '拖动滑块，对比虚构供应商说法和演示记录。', leftTitle: '供应商提供的说法', rightTitle: '查到的记录', left: ['自称成立：2014 年', '证书持有人：Lumen Harbor Devices', '报价型号：LH-65W'], right: ['登记成立：2023 年', '证书持有人：Lumen Harbor Trading', '证书仅列：LH-45W'], conclusion: '发现信息不一致：成立年份、证书持有人和型号范围均未对应。' },
      why: { label: 'ZimonAI 解决的不是搜索，而是判断', title: '服务于没有中国信息研究人员的小型海外买家。', text: '英文商号、中文法定名称、企业登记、证书图片和产品型号，往往分散在不同系统里。ZimonAI 把它们整理成一份买家能够看懂、继续追问并用于采购判断的核查报告。' },
      operating: { label: 'ZimonAI 的运营事实', title: '规模可以小，信息不能含糊。', lead: '以下是目前真实的工作方式，不需要虚构团队、客户数量或认证来装饰。', facts: [['服务对象', '客户是海外买家，项目围绕充电器与电源电子供应链展开。'], ['谁来付费', '由客户付费；不收供应商佣金或回扣，也不经手采购款。'], ['如何协作', '台湾与深圳双基地协作；实际执行范围按项目条件确认。'], ['如何给出结果', '每一项说法只会落在“信息一致、暂时无法核实、发现信息不一致”三种结果。']] },
      service1: { tier: 'Tier 1', title: '远程证照核查', price: 'USD 149', unit: '每个标准案件', time: '资料完整后 24–48 小时', text: '核对公司法律主体与状态、证书持有人和型号范围，再比较不同记录中的名称、日期和地址。', mini: ['公司身份', '证书持有人', '产品型号', '证据摘要'] },
      service2: { tier: 'Tier 2', title: '远程深度尽调', price: 'USD 349', unit: '每个标准案件', time: '资料完整后 3–5 个工作日', text: '在基础核查上增加地址性质、关联企业、股权、诉讼与制造商身份判断。', mini: ['地址性质', '股权关系', '诉讼记录', '制造身份'] },
      sources: { label: '信息来源索引', title: '该查哪个数据库，取决于供应商提出的是哪一种说法。', lead: '公司、证书、型号和销售市场不同，可查到的资料也不同。报告会标明实际使用的信息源和查询日期。', items: [['中国企业登记信息', '核对中文法定名称、统一社会信用代码、企业状态、成立日期和登记地址。'], ['CNCA 与相关认证记录', '根据公开资料核实证书是否存在、状态、发证机构和持有人。'], ['发证机构控制的产品系统', '例如核查内容涉及 UL 时，视情况查询 UL Product iQ 等产品／型号记录。'], ['不同市场的官方系统', '产品说法涉及特定市场时，再按需查询 FCC、EU NANDO、日本或其他官方信息。']] },
      demoTitle: '打开一份虚构供应商的证据档案。', demoLead: '点击任意项目，就能看到“供应商怎么说、我们去哪里查、记录写了什么、最后怎样判断”。以下只是服务界面演示，不是实时连接，也不是客户案例。',
      demoTabs: [
        { id: 'identity', label: '公司身份', source: '中国官方企业登记信息', claim: 'Lumen Harbor Devices Co., Ltd.', record: '找到对应法律主体，企业状态正常。', result: 'verified', note: '供应商提交的中文法定名称与查到的公司主体一致。' },
        { id: 'registration', label: '成立年份', source: '中国官方企业登记信息', claim: '自 2014 年开始经营', record: '登记成立日期：2023 年 3 月 18 日。', result: 'discrepancy', note: '官方登记日期无法支持“2014 年起经营”这一说法。' },
        { id: 'certificate', label: 'UL 证书', source: '发证机构控制的认证数据库', claim: '这张证书属于供应商', record: '记录持有人：Lumen Harbor Trading Co., Ltd.', result: 'discrepancy', note: '证书记录存在，但持有人名称不是供应商的法律主体。' },
        { id: 'model', label: '产品型号', source: '证书所列产品／型号范围', claim: 'LH-65W 已列入证书', record: '记录仅列出 LH-30W 和 LH-45W。', result: 'unresolved', note: '目前查到的记录中没有 LH-65W，不能把其他型号的证书直接套用。' },
        { id: 'address', label: '工厂地址', source: '企业登记和供应商文件', claim: '深圳自有工厂', record: '找到登记地址；是否在这里生产，仍需要现场核查。', result: 'unresolved', note: '登记地址只能说明地址信息存在，不能直接证明工厂活动。' }
      ],
      limitsTitle: '查到真实记录，也不代表所有风险都消失。', limitsText: '公司存在、证书有效或地址能够找到，都不能保证以后履约、产品质量和每批出货合规。把这些边界写清楚，是报告正文的一部分，不是藏在页脚的小字。', finalTitle: '手上有一家供应商，却不知道应该先查哪里？', finalText: '把公司名称、链接、证书或产品型号发来。我们会先回复能够核查什么、适合哪个层级，再决定是否开始。'
    },
    services: {
      kicker: 'T1–T6 服务', title: '先选与眼前决策相符的层级。', lead: '这是一道逐级增加的服务阶梯，不是六个互不相干的产品。往上一级，就是在前一级的证据与接触深度上继续增加。',
      staircase: { label: '先选层级', title: '六个层级，一条连续的核查路径。', lead: '点击层级即可阅读完整内容。每一级都清楚列出“不包括”与“供应商同意”，不把重要边界藏起来。' },
      sampleReport: { label: 'T1 报告样本', title: '先看完整交付内容，再决定是否购买。', lead: '这份 8 页英文样本以“XX”隐去供应商名称，完整呈现核查范围、证据对照、风险判断、限制和签约前追问清单。实际页数和内容会按案件可获取的证据调整。', facts: ['8 页 PDF', '英文样本', '供应商名称已去标识'], open: '打开完整样本报告', download: '下载 PDF' },
      labels: { price: '价格', timing: '周期', mode: '方式', important: '重要说明', notIncluded: '不包括', consent: '供应商同意', fit: '适合' },
      catalog: [
        { id: 't1', label: 'T1', title: '远程证照核查', englishTitle: 'Certificate Verification', summary: '先查供应商身份、合法性，以及充电类产品最重要的认证资料。', price: 'USD 149', timing: '资料完整后 24–48 小时', mode: '纯远程', purchasable: true, groups: [
          { title: '供应商身份与合法性', items: ['营业执照真伪与统一社会信用代码', '注册资本、成立日期与法定代表人', '经营范围是否确实包含“制造”', '经营状态：存续、异常、注销或吊销', '失信被执行人记录', '行政处罚记录'] },
          { title: '充电类专属认证比对', items: ['FCC ID 是否存在，是否对应报价型号与瓦数', 'UL 档案号是否仍然有效（UL Product iQ）', '发证实验室是否出现在 FCC 除名或过渡期名单', '以有日期、同规格的市场样本判断标示规格与报价是否合理；异常价格是需要追查的线索，不等于虚假报价的证明'] }
        ], marketReference: {
          label: '公开供应商报价观察 · 2026 年 8 月 31 日查询',
          title: '这是当期公开报价样本，不是经审计的制造成本。',
          text: '本次选取 Alibaba、Made-in-China 与 Global Sources 的非完全同规格 65W GaN 壁插式充电器；公开单价约为 USD 5.20–10.70，页面所列 MOQ 约为 50–500 件。',
          limits: '页面未一致包含或披露运费、税费、Incoterms、定制包装与认证主张的佐证。判断报价高低前，仍须逐项比对端口数、插头、协议、用料、认证证据、包装、保修、定制、数量与交付条件。',
          sources: [
            { label: 'Alibaba · 100 件起', href: 'https://www.alibaba.com/product-detail/2025-GaN-Customizing-ETL-FCC-Certificated_1601213471100.html' },
            { label: 'Made-in-China · 500 件', href: 'https://langbone.en.made-in-china.com/' },
            { label: 'Global Sources · 50 件起', href: 'https://www.globalsources.com/manufacturers/330w-dc-usb-c-gan-charger.html?pageNum=282' }
          ]
        }, delivery: '3–5 页报告，包括风险评级、疑点清单与签约前追问清单。', notIncluded: '实地核查、电话访谈、产能判断、质量检验。', consent: '不需要', fit: '首次接触中国供应商的海外买家；常见单笔采购金额 USD 5,000–30,000。' },
        { id: 't2', label: 'T2', title: '远程深度尽调', englishTitle: 'Remote Due Diligence', summary: '在 T1 基础上，再查地址性质、股权、诉讼与真实制造身份。', price: 'USD 349', timing: '资料完整后 3–5 个工作日', mode: '纯远程', purchasable: true, upgrade: '包括 T1 全部项目，再增加企业关系与公开记录的深度核查。', groups: [
          { title: 'T2 新增项目', items: ['判断注册地址属于工业区、商业区还是住宅', '关联企业与股权结构', '裁判文书网可查的法律诉讼记录', '进出口记录查询', '判断对方是制造商，还是把自己包装成制造商的贸易商', '比对 1688、阿里巴巴与官网说法是否符合登记事实'] }
        ], notIncluded: '实地核查、直接与供应商沟通、质量检验。', consent: '不需要', fit: '已经锁定供应商、但仍对其真实性存疑的买家；常见单笔采购金额 USD 30,000–100,000。' },
        { id: 't3', label: 'T3', title: '电话与视频访查', englishTitle: 'Verified Remote Interview', summary: '在 T2 基础上，直接访谈供应商并进行实时视频看厂。', price: 'USD 449–599', timing: '5–7 个工作日', mode: '远程＋视频', upgrade: '包括 T2 全部项目，再增加供应商知情同意下的直接访查。', groups: [
          { title: 'T3 新增项目', items: ['与供应商业务联系人进行结构化电话访谈', '要求视频看厂，直播查看产线、仓库与样品', '核对供应商口头陈述是否符合文件与公开信息'] }
        ], note: '如果供应商拒绝配合视频，或刻意回避特定问题，这个反应本身就是核查结果；报告会如实记录，并列为风险项。', notIncluded: '实地到场、量产监督、质量检验。', consent: '需要书面同意', fit: '准备签约、但无法亲自到中国的买家；常见单笔采购金额 USD 50,000–200,000。' },
        { id: 't4', label: 'T4', title: '单次实地核查', englishTitle: 'On-Site Verification (Single Visit)', summary: '在 T3 基础上，到厂核查一次，并抽测充电产品的关键规格。', price: 'USD 899–1,299', timing: '7–10 个工作日', mode: '远程＋一次实地', upgrade: '包括 T3 全部项目，再增加一次双方同意的到厂核查。', groups: [
          { title: '到厂核查', items: ['核对注册地址与实际经营地址是否一致', '查看厂房规模与设备', '确认产线是否正在运行', '估算现场员工人数', '现场查看样品', '按约定范围全程拍照与影像存证'] },
          { title: '充电类专属规格实测', items: ['现场抽测样品输出瓦数、接口规格与产品标示是否一致'] }
        ], notIncluded: '量产监督、完整质量检验、验货、代客采购。', consent: '需要书面同意', fit: '签约前需要实地确认的买家；常见单笔采购金额 USD 100,000 以上。' },
        { id: 't5', label: 'T5', title: '供应商核查顾问', englishTitle: 'Verification Advisor — Monthly Retainer', summary: '持续提供 T1–T3 支持，并为核心供应商建立跟踪档案。', price: 'USD 1,500–2,500／月', timing: '首月可单月试用；第二个月起每期三个月', mode: '月费顾问', upgrade: '不是单次交付，而是一段持续协作关系。', groups: [
          { title: '每月服务内容', items: ['采购过程中可随时提交供应商名称，按 T1–T2 标准在三个工作日内回复', '每月包括一次 T3 等级的深度访查', '为长期合作的核心供应商建立并维护跟踪档案'] }
        ], notIncluded: '实地核查（需另加 T4 费用）、采购决策、代客采购。', consent: '按当月工作内容确定；进行 T3 访查时需要书面同意', fit: '每月都要开发新供应商的买家、手上有十家以上供应商需要持续监控的买家，以及跨境电商采购团队。' },
        { id: 't6', label: 'T6', title: '全托管采购把关', englishTitle: 'Full Managed Sourcing Verification', summary: '整合 T4 与 T5，把核查放进整段采购流程。', price: '项目报价，USD 5,000 起', timing: '4–8 周', mode: '项目制', upgrade: '整合 T4＋T5，并把核查工作延伸到采购流程各阶段。', groups: [
          { title: '全流程把关', items: ['从候选供应商池进行筛选', '主导 RFQ 过程中的供应商比对', '在合同条款确定前完成最终尽调', '下单后进行量产前核查', '必要时安排装运前核查'] }
        ], notIncluded: '采购决策与付款执行仍由客户负责。ZimonAI 是买家的独立采购把关人，不是采购代理。', consent: '需要书面同意', fit: '大型买家、第一次进入中国采购市场的品牌，以及需要把整套采购把关流程交由专人管理的客户。' }
      ],
      promises: { label: '写进每一份报告', title: '写进每一份报告的三项承诺', lead: '一份核查报告的价值，等于撰写者独立性的价值。所以我们每一次都把这件事写在封面。', items: [['我们只收买家的钱', '不收工厂任何形式的佣金、回扣或介绍费。你支付的服务费，是我们在这个项目中的全部收入。'], ['每一项判断都标明来源', '每一项结论都附上相应的数据库、文件或照片来源。你可以自行复查任何一项。'], ['我们写清楚没有查什么', '每份报告都标明观察日期、地点与范围限制。三月核查过的工厂，不等于九月也核查过。']] },
      prepare: { label: '询价前可以准备', title: '把采购沟通中已经出现的资料提交给我们。', lead: '资料不必整理得很漂亮，但名称、编号和型号越准确，越容易判断能不能查。', items: ['供应商使用的英文商号和中文法定名称（如已知）', '官方网站、Alibaba 页面或其他供应商链接', '产品名称和完整型号', '证书图片、证书编号或数据库链接', '供应商声称的工厂／办公地址', '这次核查要支持的采购决定与时间要求'] },
      tier1: { label: 'Tier 1', title: '远程证照核查', price: 'USD 149／每个标准案件', time: '资料完整后 24–48 小时', best: '适合第一次下单、准备支付订金，或中断一段时间后重新合作前，希望先确认交易主体和文件说法的海外买家。', includes: ['核对一个中国法律主体', '核查企业状态、成立日期和登记地址', '核对最多两项证书或认证主张', '核对一个报价型号是否在证书范围', '比较公司名、日期、地址、持有人和型号', '标出找不到的证据和影响判断的信息差异'], output: '一份 3–5 页结构化报告，包含本次范围、证据比对、三种核查结果、来源记录与限制。', sequence: [['1・收件', '先固定这次要查的名称、编号、链接和供应商说法。'], ['2・找记录', '按每项说法寻找当下可获取、可信度最高的信息源。'], ['3・交叉比对', '核对主体、持有人、地址、日期和产品范围。'], ['4・写报告', '每一个结论都要能够回到记录，同时说明限制。']] },
      tier2: { label: 'Tier 2', title: '远程深度尽调', price: 'USD 349／每个标准案件', time: '资料完整后 3–5 个工作日', best: '适合已经锁定供应商，希望在商业决定前进一步查清企业背景和公开说法的买家。', includes: ['包括标准 T1 全部项目', '一家主要供应商与最多两家直接关联企业', '判断注册地址性质', '查询股权、诉讼和公开进出口线索', '判断制造商或贸易商身份', '比对平台、官网说法与登记事实'], output: '一份把企业关系、公开记录、判断依据与未解限制分开列出的远程尽调报告。', sequence: [['1・收件', '固定供应商、产品和本次决定。'], ['2・深挖记录', '查询企业关系、地址、诉讼和可获取的进出口线索。'], ['3・身份判断', '比对制造商／贸易商身份与公开说法。'], ['4・写入报告', '逐项列出依据和限制。']] },
      deliverables: { label: '报告内容', title: '一份核查报告，至少要让你看到以下六个部分。', items: [['核查范围', '本次究竟核查哪家公司、哪张证书、哪个型号、哪个地址。'], ['公司身份', '查到的中文法律主体，以及企业登记中的重要字段。'], ['证据比对表', '把供应商说法、信息来源、查询日期和记录内容并列。'], ['逐项结果', '每项分别标为信息一致、暂时无法核实或发现信息不一致。'], ['来源附件', '在适当并且可以获取时，附上链接、截图或来源记录。'], ['限制与下一步', '说明本次仍不能证明什么，以及是否需要现场核查、验货或其他专业服务。']] },
      custom: { label: '标准服务之外', title: '其他需求，先按项目确认。', text: 'T1–T6 以外的工作会另行评估；只有在范围、执行者、费用与交付内容都能说清楚时才接受。' },
      notIncluded: { title: '按项目另行确认', items: ['供应商寻找、初筛与推荐', '商业协调或议价支持', '订单、订金与付款安排', '质量检测、抽样与第三方实验室工作', '特定市场标准与验收条件', '差旅、第三方与其他代垫成本'] },
      pricingNote: 'T1 与 T2 按公开标准范围固定收费；超出范围的工作会先说明，再由你决定是否接受补充报价。必要资料不完整时，不会开始计算交付时间。', ctaTitle: '不知道应该选哪个层级？', ctaText: '如果不确定从哪里开始，可以先预约咨询；较高层级仍可先提供供应商、产品和你正要做的决定。'
    },
    methodology: {
      kicker: '核查方法', title: '每一个结论，都应该能够沿路回到原始说法和信息来源。', lead: '我们优先查找官方或发证机构控制的记录；查不到的地方就停下来，不把推测写成事实。', visualAlt: '电源板上的变压器、电容与散热片近景', mapTitle: '走一遍完整核查路径', mapLead: '点击每一步，查看具体核查什么、为什么要查、会使用哪类信息，以及最后可能得到什么结果。',
      nodes: [
        { id: 'intake', label: '供应商说法', check: '按原样保留公司名、链接、证书、型号和地址。', why: '一个字、不同主体或型号后缀，都可能让结果完全不同。', source: '买家和供应商提交的资料', results: '只是起点，还不是结论' },
        { id: 'registry', label: '企业登记', check: '中文法定名称、统一社会信用代码、企业状态、成立日期和登记地址。', why: '英文商号或店铺名称，不一定就是实际收款和签约的法律主体。', source: '中国官方企业登记／信用信息', results: '信息一致／暂时无法核实／信息不一致' },
        { id: 'certificate', label: '证书记录', check: '证书是否存在、当前状态、持有人、发证方和公开细节。', why: '供应商发来的证书图片可能已经过期、被修改，或者原本属于另一家公司。', source: '官方或发证机构控制的认证数据库', results: '信息一致／暂时无法核实／信息不一致' },
        { id: 'holder', label: '持有人关系', check: '证书持有人、供应商主体和声称的工厂是否为同一方，或者是否存在可以说明的关系。', why: '证书真实，不代表报价公司有权使用。', source: '企业与证书记录交叉比对', results: '关系成立／关系不明／主体不符' },
        { id: 'model', label: '产品型号', check: '报价的完整型号是否出现在公开可查的证书产品范围内。', why: '同一张证书往往只覆盖特定型号、版本或额定参数。', source: '证书附表和产品记录', results: '已列入／目前未找到／明确排除' },
        { id: 'crosscheck', label: '逐项比对', check: '把不同记录中的公司名、日期、地址、持有人和型号放在一起。', why: '很多矛盾只有并列之后才看得出来。', source: 'ZimonAI 证据比对表', results: '一致／仍有缺口／发现信息不一致' },
        { id: 'report', label: '核查报告', check: '每项结论都附上信息来源、查询日期、证据内容和限制。', why: '买家应该看得懂我们为什么这样判断，也能够针对某一项继续追问。', source: 'ZimonAI 核查与判断', results: '信息一致／暂时无法核实／发现信息不一致' }
      ],
      sourceRegistry: { label: '信息来源类型', title: '不是哪个网站方便就查哪个，而是先看需要证明哪一件事。', items: [['公司身份', '中国官方企业登记与信用信息', '可以查法律存在和状态，不能保证履约。'], ['中国认证', 'CNCA、认可信息或发证机构系统', '不同制度公开的字段和可查程度不同。'], ['产品与型号', 'UL Product iQ 或其他发证方控制的产品系统', '证书可能只适用于特定型号和额定参数。'], ['特定市场说法', 'FCC、EU NANDO、日本或其他官方系统', '只有供应商提出相关市场说法时才查询。']] },
      sourcesTitle: '官方信息优先，不等于只看官方信息。', sourcesText: '供应商文件和第三方资料可以帮助寻找线索或补充背景，但报告会说明它们的证据分量，不会悄悄把一张网页截图升级成官方证明。', statusesTitle: '不用黑箱分数，只保留三种容易理解的结果', statusText: ['信息一致：查到的证据支持这一项具体说法。', '暂时无法核实：目前可以获取的资料不足，无法负责地下结论。', '发现信息不一致：供应商说法与查到的记录，在重要字段上相互冲突。'], handlingTitle: '证据如何保留', handlingText: '报告会标出信息来源和查询日期，并在适当情况下附上链接、截图或来源记录。数据库可能改版、暂停或调整公开内容，因此结论只针对本次实际查到的信息。',
      reportAnatomy: { label: '一项结论的五个部分', title: '只有结果不够，还要看得懂结果是怎么来的。', items: [['供应商说法', '本次要核实的原话、文件字段或产品说明。'], ['信息来源', '实际查询的登记系统、监管机构或发证机构数据库。'], ['查到的记录', '数据库中真正出现的公司、日期、持有人或型号。'], ['判断理由', '为什么这条记录支持、不足以支持，或直接推翻供应商说法。'], ['核查限制', '即使这一项成立，仍然不能证明哪些事情。']] }
    },
    scope: {
      kicker: '服务范围', title: '先说你要做什么决定，再确认服务怎么组合。', lead: 'ZimonAI 能协助的不只是信息核查。实际工作会按供应商、产品、市场和客户决策另行确认。', visualAlt: '手持多端口 USB 电源适配器的近景', doTitle: 'ZimonAI 可以怎么协助', doItems: ['按需求寻找、初筛或推荐供应商', '核查公司、证书、型号和商业说法', '根据个案需求安排现场确认', '执行或协调产品质量检测和适当的第三方测试', '把不同证据放在一起，说明关键差异', '开始前先整理成符合个案的服务方案'], dontTitle: '开始前会先确认', dontItems: ['这次要处理的供应商、产品、型号或具体说法', '工作属于信息研究、现场确认、质量检测，还是多项组合', '质量工作要使用的标准、样品和验收条件', '需要合格第三方时，每一部分由谁执行', '费用、第三方成本、时间和交付内容', '供应商回扣不会成为推荐或结论的依据'],
      limitsTitle: '核查有这些边界', limits: [['公司真实，不等于交易一定可靠', '登记信息可以确认法律主体和当前状态，不能保证以后的交付、履约或偿付能力。'], ['证书真实，不等于所有产品都合规', '证书可能只适用于特定持有人、型号、额定参数、地点或期间，也不能证明每一件出货产品。'], ['地址存在，不等于一定是自有工厂', '登记地址或到访地址本身，不能证明工厂所有权、产能和产品质量。'], ['数据库存在时间和访问限制', '公开信息可能改版、暂停或省略字段；报告只针对标明查询日期时可以获取的内容。'], ['现场核查是公开透明的', '到访会提前预约，并在供应商知情同意下进行；不是秘密调查。']],
      decisionGuide: { label: '先选对服务', title: '同一个需求，可能需要组合几种工作。', items: [['实际签约和收款的是哪家公司？', 'ZimonAI 企业资料核查'], ['这张证书是否属于该公司并覆盖这个型号？', 'ZimonAI 证书与型号核查'], ['对外提供的地址，现场能确认什么？', 'ZimonAI 预约现场工作'], ['这批货是否符合约定规格？', 'ZimonAI 质量工作或项目内的合格合作方'], ['产品是否符合认可实验室要求？', '项目中明确指定的合格实验室']] },
      accreditationMark: '分工', accreditationTitle: '需要合格第三方时，先把分工说清楚', accreditationText: '项目需要认可测试、认证或符合性评估时，会在开始前确认合格第三方，以及它实际负责的工作范围。', ctaTitle: '需求中包括质量工作吗？', ctaText: '请提供产品、型号、目标市场与验收条件。ZimonAI 会确认哪些可以直接执行、哪些需要合格第三方，并提前说明报告方式。'
    },
    about: {
      kicker: '关于 ZimonAI', title: '专注充电器与电源电子供应链，不把自己包装成什么都懂。', lead: 'ZimonAI 智蒙灣采用台湾 × 深圳双基地协作。付费客户是海外买家，不是被核查的供应商。',
      originTitle: '为什么会有这项服务', originText: '海外买家手上经常只有英文商号、证书图片、工厂地址和看起来完整的供应商页面。真正困难的是：找到对应的中文法律主体，进入正确的数据库，再判断这些资料能不能相互对应。ZimonAI 就是把这段工作做清楚。',
      modelTitle: '由客户付费，也对客户负责', modelText: '客户有需求时，ZimonAI 可以协助寻找供应商、提供推荐、核查信息，并安排后续质量工作。推荐和核查结论不以供应商回扣为依据，每项工作的商业和交付范围都会另行确认。',
      footprintTitle: '台湾 × 深圳，双基地协作', footprintText: '从信息研究、买家沟通到现场执行，工作由台湾和深圳两地协作。实际可承接范围按需求、时间和执行条件确认，不在网站上预先划定城市名单。',
      locationsTitle: '两个办公地点，各自负责不同工作。', locationsLead: '台湾办公室负责客户联络与项目协调；深圳办公室支持公司登记与中国端执行。',
      scaleTitle: '开始工作以前，先把范围与交付说清楚', scaleText: '每个需求都会先确认要解决的问题、工作范围、周期和交付方式。只有在方法和责任都能说明清楚的情况下，才会正式承接。',
      record: { title: '服务方式与工作内容', items: [['业务范围', '充电器与电源电子供应商寻找、资料核查和质量支持'], ['主要客户', '海外小型买家、电商卖家和进口商'], ['商业原则', '由客户付费，推荐不以供应商回扣为依据'], ['远程工作', '查询中国企业、证书和产品／型号记录'], ['现场工作', '按项目需求与执行条件确认'], ['报告结果', '信息一致／暂时无法核实／发现信息不一致']] },
      registration: { label: '企业登记信息', stamp: '深圳登记主体', publicExcerpt: '完整执照', title: '不只是一个网站品牌：ZimonAI 在深圳有实际登记主体。', lead: '以下信息来自 ZimonAI 提供的营业执照，公司法定名称和注册地址按执照原文展示。', fields: { legalName: '登记法定名称', legalRepresentative: '法定代表人', entityType: '企业类型', established: '成立日期', registeredAddress: '注册及实际接待地址' }, entityType: '有限责任公司（港澳台自然人独资）', established: '2026 年 3 月 3 日', imageAlt: '深圳智蒙湾登记主体的完整营业执照', caption: '由 ZimonAI 提供并确认公开的完整营业执照图像。', disclosure: '经 ZimonAI 确认，执照上的地址同时是公司注册地址和实际接待地址；下方展示公共接待区实景。' },
      office: { label: '深圳实际接待空间', title: '是可以坐下来见面的地方，不是素材库照片。', lead: '以下是 ZimonAI 注册及实际接待地址内，客户可使用的公共接待区和会议区。', addressLabel: '注册及实际接待地址', disclosure: '照片只展示客户实际可使用的公共接待和会议区域。', photos: { lounge: { alt: 'ZimonAI 深圳接待地址的公共客户休息区', caption: '公共接待休息区和等候空间' }, meeting: { alt: 'ZimonAI 深圳接待地址的公共会议区', caption: '可用于客户沟通和文件讨论的公共会议区' }, reception: { alt: 'ZimonAI 深圳接待地址的接待前台', caption: '接待前台和出入区域' } } },
      principles: [['把结论说明白', '交代查了什么、去哪里查，还有哪些问题没有答案。'], ['优先查可追溯的记录', '能够查询官方或发证机构资料时，不拿第三方汇总页当最终证明。'], ['边界也要写进报告', '缺少证据就是缺少证据，核查结果也不等于对未来的保证。']], ctaTitle: '带来一家供应商，以及你正要做的决定。', ctaText: '我们先确认哪些说法能够核查，应该使用哪一个服务层级。'
    },
    request: {
      kicker: '说明服务需求', title: '告诉我们，你正在评估哪一家充电或电源电子供应商。', lead: '把采购沟通中已经有的资料发来。ZimonAI 会先判断适合哪个层级，再回复范围、价格和时间。', visualAlt: '白色移动电源与蓝色充电线', honest: '表单会安全发送到 ZimonAI。成功保存后，页面会显示需求编号；即使通知邮件未能送达，已经保存的需求仍会保留。', fields: { name: '你的姓名', email: '你的 Email', company: '公司名称（选填）', supplier: '供应商名称', url: '供应商网站／Alibaba 链接（选填）', chinese: '中文法定名称，如已知（选填）', product: '产品和型号', question: '你现在最想弄清楚什么？', consent: '我同意 ZimonAI 使用以上资料评估并回复这项需求。', send: '提交需求', required: '必填' }, placeholders: { name: '张先生', email: 'name@company.com', company: 'Northline Goods', supplier: '英文商号或中文法定名称', url: 'https://…', chinese: '深圳市…有限公司', product: '65W USB-C 充电器，型号 X65', question: '例如：确认企业主体、UL 档案、65W 型号范围，以及适合从 T1–T6 哪一级开始。' }, after: '提交后请保留需求编号；证书、报价单或供应商文件可以另发 Email，并在主题中注明该编号。', status: { validation: '请完成必填字段并勾选同意。', submitting: '正在安全提交…', successTitle: '需求已保存', successBody: '你的需求编号是', error: '这次没有成功保存；你填写的内容仍在页面上，请稍后重试或改用右侧 Email 联系。', rateLimit: '短时间内提交次数过多，请稍后重试。' }, directTitle: '也可以直接发送 Email', directText: '请附上供应商名称、链接、产品完整型号、证书编号，以及这次核查需要支持的决定。不要发送信用卡信息或核查不需要的身份证明。', responseTitle: '提交后的流程', responseSteps: ['先判断你的问题需要哪些资料与接触深度。', '回复适合的 T1–T6 层级、范围与报价。', '你确认范围、价格和交付时间后，才开始工作。']
    },
    privacy: { kicker: '隐私声明', title: '网站有意少收信息。', lead: '生效日期：2026 年 8 月 24 日。以下说明 ZimonAI 网站如何处理你主动提供的信息。', sections: [['浏览网站', '公开网站不使用广告 Cookie，也不建立跨网站广告档案。托管服务商可能为了安全和稳定传输处理基本系统记录。'], ['需求表单', '公开需求表单会通过 HTTPS 发送你提交的联系和业务资料，并以需求编号保存；即使通知 Email 提交失败，需求本身也不会因此丢失。'], ['你发送的内容', 'ZimonAI 会使用邮件和附件评估需求、执行双方同意的服务、回复问题，以及保存必要的商业记录。请勿提供核查不需要的信息。'], ['信息分享', 'ZimonAI 不会出售你的信息。只有在完成双方同意的工作确有需要、你要求分享，或者法律要求时，才可能提供给必要服务商或相关方。'], ['保存与权利', '商业往来只在处理需求、交付服务、保存记录和履行法律义务的合理期间内保存。你可以依法询问访问、更正或删除。'], ['联系方式', '隐私问题请发送至 simonlo@zimonai.com。']] }
  }
};
