export const portalContent = {
  en: {
    metaTitle: 'Client Portal | ZimonAI',
    metaDescription: 'Sign in to submit and track a ZimonAI supplier-verification case.',
    navLabel: 'Client portal',
    eyebrow: 'Private client workspace',
    title: 'Keep each supplier decision in one evidence file.',
    lead: 'Sign in to submit supplier and product details, follow the status of your work and keep case references together. This workspace is for ZimonAI clients and prospective clients—not suppliers under review.',
    assurances: [
      ['Your file, not a public profile', 'Case information is visible only after sign-in and is not added to the public website.'],
      ['Scope before work begins', 'Submitting a case does not create a charge. Scope, price and timing are confirmed before work starts.'],
      ['Evidence, status and limits', 'Each case keeps the question, current stage and eventual deliverable connected.']
    ],
    auth: {
      label: 'Secure sign-in',
      title: 'Open your client workspace',
      text: 'Use a Google account you control. ZimonAI uses the verified email address returned by Google to provide account access; your Google password is never shared with us.',
      google: 'Continue with Google',
      unavailable: 'Google sign-in is not configured in this local version yet.',
      unavailableDetail: 'The client workspace interface and secure data structure are ready for review. Google access will be enabled only after the OAuth credentials are added and the complete sign-in flow passes testing.',
      errorCancelled: 'Google sign-in was cancelled. Nothing was changed; you can try again when you are ready.',
      errorExpired: 'This sign-in attempt expired before it could be completed. Please start a new sign-in.',
      errorInvalid: 'We could not validate this sign-in attempt. For your protection, please start again from this page.',
      errorService: 'Google sign-in is temporarily unavailable. Please wait a moment and try again.',
      sessionEnded: 'Your secure session has ended. Sign in again to continue.',
      sessionUnavailable: 'We could not confirm your secure session. Check your connection, then refresh this page.',
      logoutSuccess: 'You have signed out securely.',
      privacy: 'How account information is handled',
      terms: 'Service and payment terms'
    },
    workspace: {
      eyebrow: 'Case desk',
      title: 'Your verification work',
      welcome: 'Signed in as',
      cases: 'My cases',
      newCase: 'Start a case',
      account: 'Account',
      logout: 'Sign out',
      loading: 'Checking your secure session…',
      loadError: 'We could not load the client workspace. Please refresh the page or contact ZimonAI.',
      casesLoading: 'Loading your case files…',
      casesError: 'Your case files could not be loaded. Refresh the page to try again; no case information was changed.',
      logoutError: 'We could not complete sign-out. Your session is still active; please try again.',
      loggingOut: 'Signing out…',
      emptyLabel: 'No case files yet',
      emptyTitle: 'Your first file starts with the exact supplier claim.',
      emptyText: 'Send the supplier, product and decision you need to make. ZimonAI will review the request and confirm the appropriate T1–T6 scope before any work or charge begins.',
      emptyAction: 'Submit your first case',
      casesTitle: 'Case ledger',
      casesLead: 'Only cases linked to this signed-in account appear here.',
      status: { submitted: 'Submitted', reviewing: 'Under review', awaiting_client: 'Waiting for your information', scoped: 'Scope confirmed', in_progress: 'In progress', delivered: 'Delivered', closed: 'Closed' },
      updated: 'Updated',
      tier: 'Service level',
      supplier: 'Supplier',
      product: 'Product',
      openCase: 'Open case'
    },
    form: {
      eyebrow: 'New case intake',
      title: 'Tell us what decision this work should support.',
      lead: 'Provide what you already have. Missing details can be clarified during scope review; do not send card numbers, passwords or unrelated identity documents.',
      sections: ['Supplier', 'Product', 'Decision'],
      supplierName: 'Supplier or trading name',
      supplierNameHint: 'Use the name shown on the quotation, marketplace page or document.',
      supplierUrl: 'Supplier link',
      chineseLegalName: 'Chinese legal name, if known',
      tier: 'Service level in mind',
      tierOptions: [['unsure', 'Not sure—recommend a level'], ['t1', 'T1 · Certificate Verification'], ['t2', 'T2 · Remote Due Diligence'], ['t3', 'T3 · Verified Remote Interview'], ['t4', 'T4 · On-Site Verification'], ['t5', 'T5 · Verification Advisor'], ['t6', 'T6 · Managed Sourcing Verification']],
      productCategory: 'Product category',
      productCategoryHint: 'For example: 65W GaN charger, power adapter or power bank.',
      productModel: 'Model or quoted specification',
      decisionContext: 'What decision are you trying to make?',
      decisionContextHint: 'For example: decide whether to pay a deposit, sign a contract or rely on a certificate.',
      requestedChecks: 'Claims or documents that concern you',
      requestedChecksHint: 'Certificate numbers, conflicting names, addresses, wattage, quotation details or other questions.',
      consent: 'I confirm that I am authorised to share this information and understand that submission does not create a charge or guarantee acceptance.',
      submit: 'Submit case for scope review',
      submitting: 'Submitting securely…',
      success: 'Case submitted. ZimonAI will review the material and confirm the next step.',
      error: 'The case could not be submitted. Review the fields and try again.',
      rateLimited: 'This account has reached the 24-hour submission limit. Your existing cases are unchanged; please try again after the time shown or contact ZimonAI.',
      openLimit: 'This account already has the maximum number of active case files. Please contact ZimonAI before opening another case.',
      required: 'Required',
      optional: 'Optional',
      cancel: 'Back to my cases'
    },
    account: {
      eyebrow: 'Account',
      title: 'Your sign-in details',
      lead: 'These details come from the Google account used to sign in. Case files and service communication remain separate from your public Google profile.',
      name: 'Name',
      email: 'Verified email',
      locale: 'Workspace language',
      accountId: 'Account reference',
      privacy: 'Read the privacy notice',
      support: 'Ask about this account',
      supportSubject: 'ZimonAI client portal account support'
    }
  },
  'zh-tw': {
    metaTitle: '客戶中心｜ZimonAI 智蒙灣',
    metaDescription: '登入 ZimonAI 客戶中心，提交並追蹤供應商查核案件。',
    navLabel: '客戶中心',
    eyebrow: '客戶專屬工作區',
    title: '每一個供應商決策，都有一份清楚的案件紀錄。',
    lead: '登入後，你可以提交供應商與產品資料、查看案件進度，並把相關編號集中保存。這是提供給 ZimonAI 客戶與準客戶的工作區，不提供受查供應商登入。',
    assurances: [
      ['案件資料不會公開', '只有登入後才能查看你的案件；內容不會自動出現在公開網站。'],
      ['先確認範圍，再開始工作', '送出案件不會立即產生費用。我們會先確認範圍、價格與時間。'],
      ['問題、進度與交付放在一起', '每一案都保留原始問題、目前階段，以及後續交付資料的關聯。']
    ],
    auth: {
      label: '安全登入',
      title: '進入你的客戶工作區',
      text: '請使用你本人可控制的 Google 帳號。ZimonAI 會以 Google 回傳的已驗證 Email 提供帳戶存取；我們不會取得你的 Google 密碼。',
      google: '使用 Google 帳號繼續',
      unavailable: '這個本機版本尚未設定 Google 登入。',
      unavailableDetail: '客戶中心介面與安全資料結構已可供檢查。只有在加入 OAuth 憑證並完成整套登入測試後，才會正式開放 Google 登入。',
      errorCancelled: '你已取消 Google 登入，帳戶資料沒有變更；準備好後可以再試一次。',
      errorExpired: '這次登入程序已逾時，請從本頁重新開始登入。',
      errorInvalid: '這次登入程序未通過安全驗證。為了保護帳戶，請從本頁重新登入。',
      errorService: 'Google 登入暫時無法使用，請稍後再試。',
      sessionEnded: '安全登入階段已結束，請重新登入後繼續。',
      sessionUnavailable: '目前無法確認安全登入狀態。請檢查網路連線後重新整理本頁。',
      logoutSuccess: '你已安全登出。',
      privacy: '我們如何處理帳戶資料',
      terms: '服務與付款條款'
    },
    workspace: {
      eyebrow: '案件工作台',
      title: '你的查核案件',
      welcome: '目前登入',
      cases: '我的案件',
      newCase: '新增案件',
      account: '帳戶',
      logout: '登出',
      loading: '正在確認安全登入狀態…',
      loadError: '目前無法載入客戶中心。請重新整理頁面，或直接聯絡 ZimonAI。',
      casesLoading: '正在載入你的案件…',
      casesError: '目前無法載入案件。請重新整理頁面再試一次；既有案件資料沒有被更動。',
      logoutError: '目前無法完成登出，你的登入狀態仍然有效，請再試一次。',
      loggingOut: '正在登出…',
      emptyLabel: '目前沒有案件',
      emptyTitle: '第一份案件，從你收到的供應商資料開始。',
      emptyText: '告訴我們供應商是誰、產品是什麼，以及你正在做哪一個決定。ZimonAI 會先判斷適合的 T1–T6 範圍，再確認是否承接、費用與時間。',
      emptyAction: '提交第一個案件',
      casesTitle: '案件紀錄',
      casesLead: '這裡只會顯示與目前登入帳戶相連的案件。',
      status: { submitted: '已送出', reviewing: '範圍審核中', awaiting_client: '等待你補充資料', scoped: '範圍已確認', in_progress: '執行中', delivered: '已交付', closed: '已結案' },
      updated: '更新時間',
      tier: '服務層級',
      supplier: '供應商',
      product: '產品',
      openCase: '查看案件'
    },
    form: {
      eyebrow: '新增案件',
      title: '先告訴我們，這次查核要幫你做什麼決定。',
      lead: '你可以先提供手邊已有的資料，缺少的細節會在範圍審核時再確認。請勿提交完整卡號、密碼或與案件無關的身分證件。',
      sections: ['供應商', '產品', '決策'],
      supplierName: '供應商名稱或對外使用名稱',
      supplierNameHint: '請依報價單、平台頁面或文件上顯示的名稱填寫。',
      supplierUrl: '供應商連結',
      chineseLegalName: '中國公司法定名稱（如已知）',
      tier: '目前考慮的服務層級',
      tierOptions: [['unsure', '不確定，請協助判斷'], ['t1', 'T1 · 遠端證照查核'], ['t2', 'T2 · 遠端深度盡調'], ['t3', 'T3 · 電話與視訊訪查'], ['t4', 'T4 · 單次實地查核'], ['t5', 'T5 · 供應商查核顧問'], ['t6', 'T6 · 全託管採購把關']],
      productCategory: '產品類型',
      productCategoryHint: '例如：65W GaN 充電器、電源適配器或行動電源。',
      productModel: '型號或報價規格',
      decisionContext: '你正在做哪一個決定？',
      decisionContextHint: '例如：是否支付訂金、簽署合約，或能否採信某張證書。',
      requestedChecks: '你最在意的宣稱、文件或疑點',
      requestedChecksHint: '可以填寫證書編號、公司名稱不一致、地址、瓦數、報價或其他問題。',
      consent: '我確認自己有權提供這些資料，並了解送出案件不會立即產生費用，也不代表 ZimonAI 已經承接。',
      submit: '送出案件，確認查核範圍',
      submitting: '正在安全送出…',
      success: '案件已送出。ZimonAI 會先檢視資料，再向你確認下一步。',
      error: '案件未能送出，請檢查欄位後再試一次。',
      rateLimited: '這個帳戶已達 24 小時內的送件上限；既有案件不受影響。請稍後再試，或直接聯絡 ZimonAI。',
      openLimit: '這個帳戶的進行中案件已達上限。新增案件前，請先聯絡 ZimonAI。',
      required: '必填',
      optional: '選填',
      cancel: '返回我的案件'
    },
    account: {
      eyebrow: '帳戶',
      title: '你的登入資料',
      lead: '以下資料來自你用來登入的 Google 帳號。案件內容與服務往來不會公開到你的 Google 個人檔案。',
      name: '姓名',
      email: '已驗證 Email',
      locale: '工作區語言',
      accountId: '帳戶編號',
      privacy: '查看隱私聲明',
      support: '詢問帳戶問題',
      supportSubject: 'ZimonAI 客戶中心帳戶協助'
    }
  },
  'zh-cn': {
    metaTitle: '客户中心｜ZimonAI 智蒙湾',
    metaDescription: '登录 ZimonAI 客户中心，提交并跟进供应商核查项目。',
    navLabel: '客户中心',
    eyebrow: '客户专属工作区',
    title: '每一次供应商决策，都有一份清楚的项目记录。',
    lead: '登录后，你可以提交供应商和产品资料、查看项目进度，并集中保存相关编号。这是面向 ZimonAI 客户与潜在客户的工作区，不向被核查的供应商开放。',
    assurances: [
      ['项目资料不会公开', '只有登录后才能查看你的项目；内容不会自动出现在公开网站。'],
      ['先确认范围，再开始工作', '提交项目不会立即产生费用。我们会先确认范围、价格和时间。'],
      ['问题、进度与交付集中管理', '每个项目都会保留原始问题、当前阶段，以及后续交付资料之间的关联。']
    ],
    auth: {
      label: '安全登录',
      title: '进入你的客户工作区',
      text: '请使用你本人可以控制的 Google 账号。ZimonAI 会使用 Google 返回的已验证邮箱提供账户访问；我们不会取得你的 Google 密码。',
      google: '使用 Google 账号继续',
      unavailable: '这个本地版本尚未配置 Google 登录。',
      unavailableDetail: '客户中心界面与安全数据结构已经可以检查。只有在添加 OAuth 凭据并完成整套登录测试后，才会正式开放 Google 登录。',
      errorCancelled: '你已取消 Google 登录，账户资料没有变更；准备好后可以重试。',
      errorExpired: '本次登录流程已超时，请从本页重新开始登录。',
      errorInvalid: '本次登录流程未通过安全验证。为了保护账户，请从本页重新登录。',
      errorService: 'Google 登录暂时不可用，请稍后重试。',
      sessionEnded: '安全登录会话已结束，请重新登录后继续。',
      sessionUnavailable: '目前无法确认安全登录状态。请检查网络连接后刷新本页。',
      logoutSuccess: '你已安全退出登录。',
      privacy: '我们如何处理账户资料',
      terms: '服务与付款条款'
    },
    workspace: {
      eyebrow: '项目工作台',
      title: '你的核查项目',
      welcome: '当前登录',
      cases: '我的项目',
      newCase: '新建项目',
      account: '账户',
      logout: '退出登录',
      loading: '正在确认安全登录状态…',
      loadError: '目前无法加载客户中心。请刷新页面，或直接联系 ZimonAI。',
      casesLoading: '正在加载你的项目…',
      casesError: '目前无法加载项目。请刷新页面后重试；已有项目资料没有被更改。',
      logoutError: '目前无法完成退出登录，你的登录状态仍然有效，请重试。',
      loggingOut: '正在退出…',
      emptyLabel: '目前没有项目',
      emptyTitle: '第一个项目，从你收到的供应商资料开始。',
      emptyText: '告诉我们供应商是谁、产品是什么，以及你正在做哪一个决定。ZimonAI 会先判断适合的 T1–T6 范围，再确认是否承接、费用与时间。',
      emptyAction: '提交第一个项目',
      casesTitle: '项目记录',
      casesLead: '这里只会显示与当前登录账户相连的项目。',
      status: { submitted: '已提交', reviewing: '范围审核中', awaiting_client: '等待你补充资料', scoped: '范围已确认', in_progress: '执行中', delivered: '已交付', closed: '已结项' },
      updated: '更新时间',
      tier: '服务层级',
      supplier: '供应商',
      product: '产品',
      openCase: '查看项目'
    },
    form: {
      eyebrow: '新建项目',
      title: '先告诉我们，这次核查需要帮助你做什么决定。',
      lead: '你可以先提供手头已有的资料，缺少的细节会在范围审核时再确认。请勿提交完整卡号、密码或与项目无关的身份证件。',
      sections: ['供应商', '产品', '决策'],
      supplierName: '供应商名称或对外使用名称',
      supplierNameHint: '请按照报价单、平台页面或文件上显示的名称填写。',
      supplierUrl: '供应商链接',
      chineseLegalName: '中国公司法定名称（如已知）',
      tier: '目前考虑的服务层级',
      tierOptions: [['unsure', '不确定，请协助判断'], ['t1', 'T1 · 远程证照核查'], ['t2', 'T2 · 远程深度尽调'], ['t3', 'T3 · 电话与视频访查'], ['t4', 'T4 · 单次实地核查'], ['t5', 'T5 · 供应商核查顾问'], ['t6', 'T6 · 全托管采购把关']],
      productCategory: '产品类型',
      productCategoryHint: '例如：65W GaN 充电器、电源适配器或移动电源。',
      productModel: '型号或报价规格',
      decisionContext: '你正在做哪一个决定？',
      decisionContextHint: '例如：是否支付订金、签署合同，或能否采信某张证书。',
      requestedChecks: '你最在意的说法、文件或疑点',
      requestedChecksHint: '可以填写证书编号、公司名称不一致、地址、功率、报价或其他问题。',
      consent: '我确认自己有权提供这些资料，并了解提交项目不会立即产生费用，也不代表 ZimonAI 已经承接。',
      submit: '提交项目，确认核查范围',
      submitting: '正在安全提交…',
      success: '项目已提交。ZimonAI 会先查看资料，再向你确认下一步。',
      error: '项目未能提交，请检查字段后重试。',
      rateLimited: '这个账户已达到 24 小时内的提交上限；已有项目不受影响。请稍后重试，或直接联系 ZimonAI。',
      openLimit: '这个账户的进行中项目已达到上限。新增项目以前，请先联系 ZimonAI。',
      required: '必填',
      optional: '选填',
      cancel: '返回我的项目'
    },
    account: {
      eyebrow: '账户',
      title: '你的登录资料',
      lead: '以下资料来自你用于登录的 Google 账号。项目内容与服务沟通不会公开到你的 Google 个人资料。',
      name: '姓名',
      email: '已验证邮箱',
      locale: '工作区语言',
      accountId: '账户编号',
      privacy: '查看隐私声明',
      support: '咨询账户问题',
      supportSubject: 'ZimonAI 客户中心账户支持'
    }
  }
};
