export const portalContent = {
  en: {
    metaTitle: 'Client Portal | ZimonAI',
    metaDescription: 'Sign in to review ZimonAI orders, case progress and available reports.',
    navLabel: 'Client portal',
    eyebrow: 'Private client workspace',
    title: 'Keep each supplier decision in one evidence file.',
    lead: 'Sign in to review confirmed orders, follow active verification work and keep case references and reports together.',
    assurances: [
      ['Your records stay private', 'Case and order information is visible only after sign-in and is not added to the public website.'],
      ['Cases open after confirmation', 'A case is created after an eligible payment or after ZimonAI confirms the requirement with you directly.'],
      ['Progress and reports stay connected', 'Each case keeps its current stage, delivery timing and available report together.']
    ],
    auth: {
      label: 'Secure sign-in',
      title: 'Open your client workspace',
      google: 'Continue with Google',
      divider: 'or use Email',
      emailLabel: 'Email address',
      emailPlaceholder: 'name@company.com',
      emailSend: 'Send verification code',
      emailSending: 'Sending code…',
      emailHelp: 'Company Email, Gmail, Outlook and any other address that can receive mail are supported.',
      codeTitle: 'Enter the 6-digit code',
      codeHint: 'We sent a short-lived code to the Email address above.',
      codeLabel: 'Verification code',
      codeVerify: 'Verify and continue',
      codeVerifying: 'Verifying…',
      codeResend: 'Use a different Email or resend',
      emailSent: 'Code sent. Check your inbox and spam folder.',
      emailRequestError: 'We could not send a code. Check the Email address and try again.',
      emailVerifyError: 'That code could not be verified. Check all six digits and try again.',
      emailExpired: 'That code has expired. Request a new code to continue.',
      emailRateLimited: 'Too many requests were made. Please wait before requesting another code.',
      unavailable: 'Sign-in is temporarily unavailable.',
      unavailableDetail: 'ZimonAI has paused new sign-ins while completing a security or service check. No account, case or order data has been changed. Please try again later or contact ZimonAI.',
      errorCancelled: 'Google sign-in was cancelled. Nothing was changed; you can try again when you are ready.',
      errorExpired: 'This sign-in attempt expired before it could be completed. Please start a new sign-in.',
      errorInvalid: 'We could not validate this sign-in attempt. For your protection, please start again from this page.',
      errorEmailLinkRequired: 'This email address is already linked to an existing account. Sign in with an email verification code instead.',
      errorService: 'Google sign-in is temporarily unavailable. Please wait a moment and try again.',
      sessionEnded: 'Your secure session has ended. Sign in again to continue.',
      sessionUnavailable: 'We could not confirm your secure session. Check your connection, then refresh this page.',
      logoutSuccess: 'You have signed out securely.',
      privacy: 'How account information is handled',
      terms: 'Service and payment terms'
    },
    workspace: {
      eyebrow: 'Case desk',
      title: 'Your verification work',
      welcome: 'Signed in as',
      cases: 'My cases',
      orders: 'Orders & payments',
      account: 'Account',
      logout: 'Sign out',
      loading: 'Checking your secure session…',
      loadError: 'We could not load the client workspace. Please refresh the page or contact ZimonAI.',
      casesLoading: 'Loading your case files…',
      casesError: 'Your case files could not be loaded. Refresh the page to try again; no case information was changed.',
      ordersLoading: 'Loading your order records…',
      ordersError: 'Your order records could not be loaded. Refresh the page to try again; no order information was changed.',
      ordersEyebrow: 'Order records',
      ordersTitle: 'Orders and payments',
      ordersLead: 'Only recorded orders linked to this signed-in account appear here. Payment status is confirmed by the server.',
      ordersEmptyLabel: 'No order records yet',
      ordersEmptyTitle: 'Orders linked to this account will appear here when they are recorded, with their current payment status.',
      ordersEmptyText: 'Orders appear after checkout or after ZimonAI records an agreed service.',
      logoutError: 'We could not complete sign-out. Your session is still active; please try again.',
      loggingOut: 'Signing out…',
      emptyLabel: 'No case files yet',
      emptyTitle: 'No verification case has been opened for this account.',
      emptyText: 'An eligible T1 or T2 payment opens a case automatically. For any other requirement, contact ZimonAI so we can confirm the scope with you before creating a case.',
      emptyAction: 'View services and prices',
      supportAction: 'Contact ZimonAI',
      supportSubject: 'ZimonAI service and case assistance',
      casesTitle: 'Case ledger',
      casesEyebrow: 'Cases and progress',
      casesLead: 'Only cases linked to this signed-in account appear here.',
      tierOptions: [['unsure', 'Not yet confirmed'], ['t1', 'T1 · Certificate Verification'], ['t2', 'T2 · Remote Due Diligence'], ['t3', 'T3 · Verified Remote Interview'], ['t4', 'T4 · On-Site Verification'], ['t5', 'T5 · Verification Advisor'], ['t6', 'T6 · Managed Sourcing Verification']],
      status: { submitted: 'Information received', reviewing: 'Scope review', awaiting_client: 'Waiting for your information', scoped: 'Scope confirmed', in_progress: 'In progress', delivered: 'Report ready', closed: 'Closed' },
      orderStatus: { pending: 'Pending', unpaid: 'Awaiting payment', paid: 'Paid', waived: 'No payment required', refunded: 'Refunded', failed: 'Payment failed', expired: 'Expired' },
      updated: 'Updated',
      ordered: 'Order date',
      amount: 'Amount',
      paymentStatus: 'Payment status',
      tier: 'Service level',
      supplier: 'Supplier',
      product: 'Product',
      openCase: 'Open case',
      progressUpdate: 'Latest progress update',
      expectedDelivery: 'Expected delivery',
      report: 'Report',
      openReport: 'Open report',
      showHiddenOrders: 'Show hidden orders',
      hideHiddenOrders: 'Hide hidden orders',
      cancelOrder: 'Cancel unpaid order',
      hideOrder: 'Hide from this list',
      restoreOrder: 'Restore to this list',
      cancelledOrder: 'Cancelled',
      cancelOrderConfirm: 'Cancel this unpaid order? No payment will be taken.',
      orderActionWorking: 'Updating…',
      orderActionError: 'This order could not be updated. Nothing was changed.',
      orderCancelled: 'The unpaid order was cancelled.',
      orderHidden: 'The order was hidden from your default list.',
      orderRestored: 'The order was restored to your list.'
    },
    account: {
      eyebrow: 'Account',
      title: 'Your sign-in details',
      lead: 'This page shows the verified email used to sign in and your ZimonAI workspace reference.',
      email: 'Verified email',
      locale: 'Workspace language',
      accountId: 'Account reference',
      privacy: 'Read the privacy notice',
      support: 'Ask about this account',
      supportSubject: 'ZimonAI client portal account support',
      admin: 'Open operations workspace',
      adminLead: 'Administrator tools are available for this account.'
    }
  },
  'zh-tw': {
    metaTitle: '客戶中心｜ZimonAI 智蒙灣',
    metaDescription: '登入 ZimonAI 客戶中心，查看訂單、案件進度與可下載的報告。',
    navLabel: '客戶中心',
    eyebrow: '客戶專屬工作區',
    title: '每一個供應商決策，都有一份清楚的案件紀錄。',
    lead: '登入後，你可以查看已確認的訂單、追蹤查核進度，並集中保存案件編號與報告。',
    assurances: [
      ['案件與訂單資料不會公開', '只有登入後才能查看你的紀錄；內容不會自動出現在公開網站。'],
      ['付款或確認後才開案', '完成適用的線上付款，或由 ZimonAI 與你確認需求後，才會建立案件。'],
      ['進度與報告放在一起', '每一案都會集中顯示目前階段、預計交付時間與可下載的報告。']
    ],
    auth: {
      label: '安全登入',
      title: '進入你的客戶工作區',
      google: '使用 Google 帳號繼續',
      divider: '或使用 Email',
      emailLabel: 'Email',
      emailPlaceholder: 'name@company.com',
      emailSend: '寄送驗證碼',
      emailSending: '正在寄送…',
      emailHelp: '公司信箱、Gmail、Outlook 與其他可正常收信的 Email 都能使用。',
      codeTitle: '輸入 6 位數驗證碼',
      codeHint: '驗證碼已寄到上方 Email，並會在短時間後失效。',
      codeLabel: '驗證碼',
      codeVerify: '驗證並繼續',
      codeVerifying: '正在驗證…',
      codeResend: '改用其他 Email 或重新寄送',
      emailSent: '驗證碼已寄出，請一併查看垃圾郵件匣。',
      emailRequestError: '目前無法寄出驗證碼，請確認 Email 後再試一次。',
      emailVerifyError: '驗證碼無法通過，請確認六位數字後再試一次。',
      emailExpired: '這組驗證碼已失效，請重新取得一組。',
      emailRateLimited: '短時間內嘗試次數過多，請稍後再取得驗證碼。',
      unavailable: '登入目前暫時停用。',
      unavailableDetail: 'ZimonAI 正在完成安全或服務檢查，期間暫停新的登入。既有帳戶、案件與訂單資料不受影響；你可以稍後再試，或直接聯絡 ZimonAI。',
      errorCancelled: '你已取消 Google 登入，帳戶資料沒有變更；準備好後可以再試一次。',
      errorExpired: '這次登入程序已逾時，請從本頁重新開始登入。',
      errorInvalid: '這次登入程序未通過安全驗證。為了保護帳戶，請從本頁重新登入。',
      errorEmailLinkRequired: '這個 Email 已連結至既有帳戶，請改用 Email 驗證碼登入。',
      errorService: 'Google 登入暫時無法使用，請稍後再試。',
      sessionEnded: '安全登入階段已結束，請重新登入後繼續。',
      sessionUnavailable: '目前無法確認安全登入狀態。請檢查網路連線後重新整理本頁。',
      logoutSuccess: '你已安全登出。',
      privacy: '我們如何處理帳戶資料',
      terms: '服務與付款條款'
    },
    workspace: {
      eyebrow: '案件工作台',
      title: '你的查核案件',
      welcome: '目前登入',
      cases: '我的案件',
      orders: '訂單與付款',
      account: '帳戶',
      logout: '登出',
      loading: '正在確認安全登入狀態…',
      loadError: '目前無法載入客戶中心。請重新整理頁面，或直接聯絡 ZimonAI。',
      casesLoading: '正在載入你的案件…',
      casesError: '目前無法載入案件。請重新整理頁面再試一次；既有案件資料沒有被更動。',
      ordersLoading: '正在載入你的訂單紀錄…',
      ordersError: '目前無法載入訂單。請重新整理頁面再試一次；既有訂單資料沒有被更動。',
      ordersEyebrow: '訂單紀錄',
      ordersTitle: '訂單與付款',
      ordersLead: '這裡只顯示與目前登入帳戶相連的訂單；付款狀態以伺服器確認結果為準。',
      ordersEmptyLabel: '目前沒有訂單紀錄',
      ordersEmptyTitle: '與這個帳戶相連的訂單建立後，就會顯示在這裡，並標示目前的付款狀態。',
      ordersEmptyText: '完成線上結帳，或由 ZimonAI 記錄已確認的服務後，訂單才會顯示在這裡。',
      logoutError: '目前無法完成登出，你的登入狀態仍然有效，請再試一次。',
      loggingOut: '正在登出…',
      emptyLabel: '目前沒有案件',
      emptyTitle: '這個帳戶目前沒有查核案件。',
      emptyText: '完成適用的 T1 或 T2 付款後，系統會自動建立案件。其他需求請先聯絡 ZimonAI，由我們一對一確認範圍後建立。',
      emptyAction: '查看服務與價格',
      supportAction: '聯絡 ZimonAI',
      supportSubject: 'ZimonAI 服務與案件協助',
      casesTitle: '案件紀錄',
      casesEyebrow: '案件與進度',
      casesLead: '這裡只會顯示與目前登入帳戶相連的案件。',
      tierOptions: [['unsure', '尚未確認'], ['t1', 'T1 · 遠端證照查核'], ['t2', 'T2 · 遠端深度盡調'], ['t3', 'T3 · 電話與視訊訪查'], ['t4', 'T4 · 單次實地查核'], ['t5', 'T5 · 供應商查核顧問'], ['t6', 'T6 · 全託管採購把關']],
      status: { submitted: '資料已收到', reviewing: '確認服務範圍', awaiting_client: '等待你補充資料', scoped: '範圍已確認', in_progress: '查核進行中', delivered: '報告已完成', closed: '已結案' },
      orderStatus: { pending: '待確認', unpaid: '等待付款', paid: '已付款', waived: '不需付款', refunded: '已退款', failed: '付款失敗', expired: '已失效' },
      updated: '更新時間',
      ordered: '訂單日期',
      amount: '金額',
      paymentStatus: '付款狀態',
      tier: '服務層級',
      supplier: '供應商',
      product: '產品',
      openCase: '查看案件',
      progressUpdate: '最新進度',
      expectedDelivery: '預計交付時間',
      report: '報告',
      openReport: '開啟報告',
      showHiddenOrders: '顯示已隱藏訂單',
      hideHiddenOrders: '收起已隱藏訂單',
      cancelOrder: '取消未付款訂單',
      hideOrder: '從清單隱藏',
      restoreOrder: '恢復到清單',
      cancelledOrder: '已取消',
      cancelOrderConfirm: '確定取消這筆未付款訂單嗎？這次不會扣款。',
      orderActionWorking: '正在更新…',
      orderActionError: '目前無法更新這筆訂單，任何資料都沒有被更動。',
      orderCancelled: '未付款訂單已取消。',
      orderHidden: '這筆訂單已從預設清單隱藏。',
      orderRestored: '這筆訂單已恢復到清單。'
    },
    account: {
      eyebrow: '帳戶',
      title: '你的登入資料',
      lead: '這裡只顯示登入使用的已驗證 Email，以及 ZimonAI 客戶中心的帳戶資料。',
      email: '已驗證 Email',
      locale: '工作區語言',
      accountId: '帳戶編號',
      privacy: '查看隱私聲明',
      support: '詢問帳戶問題',
      supportSubject: 'ZimonAI 客戶中心帳戶協助',
      admin: '開啟營運工作台',
      adminLead: '這個帳戶具有管理員權限。'
    }
  },
  'zh-cn': {
    metaTitle: '客户中心｜ZimonAI 智蒙湾',
    metaDescription: '登录 ZimonAI 客户中心，查看订单、项目进度与可下载的报告。',
    navLabel: '客户中心',
    eyebrow: '客户专属工作区',
    title: '每一次供应商决策，都有一份清楚的项目记录。',
    lead: '登录后，你可以查看已确认的订单、跟进核查进度，并集中保存项目编号与报告。',
    assurances: [
      ['项目与订单资料不会公开', '只有登录后才能查看你的记录；内容不会自动出现在公开网站。'],
      ['付款或确认后才立项', '完成适用的在线付款，或由 ZimonAI 与你确认需求后，才会创建项目。'],
      ['进度与报告集中管理', '每个项目都会集中显示当前阶段、预计交付时间与可下载的报告。']
    ],
    auth: {
      label: '安全登录',
      title: '进入你的客户工作区',
      google: '使用 Google 账号继续',
      divider: '或使用邮箱',
      emailLabel: '邮箱',
      emailPlaceholder: 'name@company.com',
      emailSend: '发送验证码',
      emailSending: '正在发送…',
      emailHelp: '公司邮箱、Gmail、Outlook 和其他可以正常收信的邮箱都能使用。',
      codeTitle: '输入 6 位验证码',
      codeHint: '验证码已发送到上方邮箱，并会在短时间后失效。',
      codeLabel: '验证码',
      codeVerify: '验证并继续',
      codeVerifying: '正在验证…',
      codeResend: '更换邮箱或重新发送',
      emailSent: '验证码已发送，请同时查看垃圾邮件文件夹。',
      emailRequestError: '目前无法发送验证码，请确认邮箱后重试。',
      emailVerifyError: '验证码未能通过，请确认六位数字后重试。',
      emailExpired: '这组验证码已失效，请重新获取。',
      emailRateLimited: '短时间内尝试次数过多，请稍后再获取验证码。',
      unavailable: '登录目前暂时停用。',
      unavailableDetail: 'ZimonAI 正在完成安全或服务检查，期间暂停新的登录。现有账户、项目与订单资料不受影响；你可以稍后重试，或直接联系 ZimonAI。',
      errorCancelled: '你已取消 Google 登录，账户资料没有变更；准备好后可以重试。',
      errorExpired: '本次登录流程已超时，请从本页重新开始登录。',
      errorInvalid: '本次登录流程未通过安全验证。为了保护账户，请从本页重新登录。',
      errorEmailLinkRequired: '这个邮箱已关联现有账户，请改用邮箱验证码登录。',
      errorService: 'Google 登录暂时不可用，请稍后重试。',
      sessionEnded: '安全登录会话已结束，请重新登录后继续。',
      sessionUnavailable: '目前无法确认安全登录状态。请检查网络连接后刷新本页。',
      logoutSuccess: '你已安全退出登录。',
      privacy: '我们如何处理账户资料',
      terms: '服务与付款条款'
    },
    workspace: {
      eyebrow: '项目工作台',
      title: '你的核查项目',
      welcome: '当前登录',
      cases: '我的项目',
      orders: '订单与付款',
      account: '账户',
      logout: '退出登录',
      loading: '正在确认安全登录状态…',
      loadError: '目前无法加载客户中心。请刷新页面，或直接联系 ZimonAI。',
      casesLoading: '正在加载你的项目…',
      casesError: '目前无法加载项目。请刷新页面后重试；已有项目资料没有被更改。',
      ordersLoading: '正在加载你的订单记录…',
      ordersError: '目前无法加载订单。请刷新页面后重试；已有订单资料没有被更改。',
      ordersEyebrow: '订单记录',
      ordersTitle: '订单与付款',
      ordersLead: '这里只显示与当前登录账户相连的订单；付款状态以服务器确认结果为准。',
      ordersEmptyLabel: '目前没有订单记录',
      ordersEmptyTitle: '与该账户关联的订单创建后会显示在这里，并标明当前付款状态。',
      ordersEmptyText: '完成在线结账，或由 ZimonAI 记录已确认的服务后，订单才会显示在这里。',
      logoutError: '目前无法完成退出登录，你的登录状态仍然有效，请重试。',
      loggingOut: '正在退出…',
      emptyLabel: '目前没有项目',
      emptyTitle: '这个账户目前没有核查项目。',
      emptyText: '完成适用的 T1 或 T2 付款后，系统会自动创建项目。其他需求请先联系 ZimonAI，由我们一对一确认范围后创建。',
      emptyAction: '查看服务与价格',
      supportAction: '联系 ZimonAI',
      supportSubject: 'ZimonAI 服务与项目协助',
      casesTitle: '项目记录',
      casesEyebrow: '项目与进度',
      casesLead: '这里只会显示与当前登录账户相连的项目。',
      tierOptions: [['unsure', '尚未确认'], ['t1', 'T1 · 远程证照核查'], ['t2', 'T2 · 远程深度尽调'], ['t3', 'T3 · 电话与视频访查'], ['t4', 'T4 · 单次实地核查'], ['t5', 'T5 · 供应商核查顾问'], ['t6', 'T6 · 全托管采购把关']],
      status: { submitted: '资料已收到', reviewing: '确认服务范围', awaiting_client: '等待你补充资料', scoped: '范围已确认', in_progress: '核查进行中', delivered: '报告已完成', closed: '已结项' },
      orderStatus: { pending: '待确认', unpaid: '等待付款', paid: '已付款', waived: '无需付款', refunded: '已退款', failed: '付款失败', expired: '已失效' },
      updated: '更新时间',
      ordered: '订单日期',
      amount: '金额',
      paymentStatus: '付款状态',
      tier: '服务层级',
      supplier: '供应商',
      product: '产品',
      openCase: '查看项目',
      progressUpdate: '最新进度',
      expectedDelivery: '预计交付时间',
      report: '报告',
      openReport: '打开报告',
      showHiddenOrders: '显示已隐藏订单',
      hideHiddenOrders: '收起已隐藏订单',
      cancelOrder: '取消未付款订单',
      hideOrder: '从列表隐藏',
      restoreOrder: '恢复到列表',
      cancelledOrder: '已取消',
      cancelOrderConfirm: '确定取消这笔未付款订单吗？本次不会扣款。',
      orderActionWorking: '正在更新…',
      orderActionError: '目前无法更新这笔订单，任何资料都没有被更改。',
      orderCancelled: '未付款订单已取消。',
      orderHidden: '这笔订单已从默认列表隐藏。',
      orderRestored: '这笔订单已恢复到列表。'
    },
    account: {
      eyebrow: '账户',
      title: '你的登录资料',
      lead: '这里只显示登录使用的已验证邮箱，以及 ZimonAI 客户中心的账户资料。',
      email: '已验证邮箱',
      locale: '工作区语言',
      accountId: '账户编号',
      privacy: '查看隐私声明',
      support: '咨询账户问题',
      supportSubject: 'ZimonAI 客户中心账户支持',
      admin: '打开运营工作台',
      adminLead: '这个账户具有管理员权限。'
    }
  }
};
